FEMALE_NAMES_NOT_ENDING_IN_A = {
    "a. barb.",
    "a. elis.",
    "a. elisab.",
    "a. kath.",
    "a. marg.",
    "adele",
    "adeline",
    "adèle",
    "agathe",
    "agn.",
    "agnes",
    "albertine",
    "alice",
    "aline",
    "amalie",
    "amelie",
    "amélie",
    "anna barb.",
    "anna elis.",
    "anna elisab.",
    "anna elisabeth",
    "anna elise",
    "anna kath.",
    "anna m.",
    "anna magd.",
    "anna marg.",
    "anna marie",
    "antoinette",
    "antonie",
    "augustine",
    "babette",
    "barb.",
    "betty",
    "blanche",
    "carol.",
    "caroline",
    "cath.",
    "cecile",
    "charlotte",
    "christiane",
    "christine",
    "clementine",
    "clotilde",
    "cäc.",
    "cäcilie",
    "cécile",
    "célestine",
    "doroth.",
    "edith",
    "eleonore",
    "elis.",
    "elisab.",
    "elisab. part.",
    "elisabeth",
    "elise",
    "elsbeth",
    "else",
    "emile",
    "emilie",
    "emma luise",
    "emmy",
    "ernest",
    "ernestine",
    "esther",
    "eugenie",
    "fanny",
    "felicitas",
    "florentine",
    "florine",
    "friederike",
    "georgette",
    "georgine",
    "gertr.",
    "gertrud",
    "gertrude",
    "hedwig",
    "helene",
    "henriette",
    "hermine",
    "hortense",
    "hélène",
    "jakobine",
    "jeanne",
    "jeannette",
    "jenny",
    "josefine",
    "josephine",
    "judith",
    "juliane",
    "julie",
    "juliette",
    "justine",
    "karol",
    "karol.",
    "karoline",
    "kath.",
    "kath. barb.",
    "kath. elis.",
    "kath. elisab.",
    "kath. part.",
    "kath. tagl.",
    "kathar.",
    "katharine",
    "kunigunde",
    "laure",
    "leonie",
    "leontine",
    "leopoldine",
    "lily",
    "lis.",
    "lisette",
    "louise",
    "lucie",
    "luise",
    "léonie",
    "m. elis.",
    "m. elisab.",
    "m. jos.",
    "m. kath.",
    "m. luise",
    "m. magd.",
    "m. marg.",
    "m. ros.",
    "magd.",
    "magdal.",
    "marg.",
    "marg. elis.",
    "margar.",
    "margarete",
    "marguerite",
    "maria a.",
    "maria barb.",
    "maria elis.",
    "maria elisab.",
    "maria elisabeth",
    "maria jos.",
    "maria karol.",
    "maria kath.",
    "maria louise",
    "maria luise",
    "maria magd.",
    "maria marg.",
    "maria urs.",
    "marianne",
    "marie",
    "marie elisab.",
    "marie luise",
    "mathilde",
    "melanie",
    "ottilie",
    "ottlie",
    "pauline",
    "philippine",
    "philomene",
    "regine",
    "ros.",
    "ros. kath.",
    "ros. marg.",
    "rosalie",
    "rose",
    "rosette",
    "rosine",
    "sab.",
    "salome",
    "sarah",
    "seline",
    "seraf.",
    "seraph.",
    "sofie",
    "soph.",
    "sophie",
    "sophie elisab.",
    "stefanie",
    "stephanie",
    "sus.",
    "sus. kath.",
    "susanne",
    "suzanne",
    "ther.",
    "theres",
    "theres.",
    "therese",
    "valerie",
    "virginie",
    "wilhelmine",
    "yvonne",
}
