HISTORICAL_STREET_NAMES_BASEL = {
    "Nauentunnel",
    "Cedernweg",
    "Lachenstrasse",
    "Spalenberg",
    "Salmenweg",
    "Oberalpstrasse",
    "Murbacherstrasse",
    "Aeschenvorstadt",
    "Kellergässlein",
    "Saint-Louis-Strasse",
    "Friedensgasse",
    "Ampereplatz",
    "Am Umschlagbahnhof",
    "Sierenzerstrasse",
    "Im tiefen Boden",
    "Flamingosteg",
    "St. Alban-Ring",
    "Schäublinstrasse",
    "Waldenburgerstrasse",
    "Hauensteinstrasse",
    "Eglisee-Parkplatz",
    "Wiesendamm",
    "Augsterweg",
    "Rehhagstrasse",
    "St. Albanteich-Promenade",
    "Biascastrasse",
    "Hamburg-Strasse",
    "Rotbergerstrasse",
    "Maulbeerstrasse",
    "Zeughausstrasse",
    "Mörsbergerstrasse",
    "Käferholzstrasse",
    "Kasernenhof",
    "Wettsteinstrasse",
    "Gottesackerstrasse",
    "Schiffmühlestrasse",
    "Totengässlein",
    "Münchensteinerbrücke",
    "Egliseeweglein",
    "Arnold Böcklin-Strasse",
    "Allmendstrasse",
    "Bruderholzweg",
    "Hochbergersteg",
    "Grellingerstrasse",
    "Hebelplatz",
    "Im Davidsboden",
    "St. Johanns-Hafen-Weg",
    "Fäschengasse",
    "Pfirtergasse",
    "Neuweilerplatz",
    "Schlettstadterstrasse",
    "Nauen-Unterführung",
    "Wittlingerstrasse",
    "Stachelrain",
    "Pilatusstrasse",
    "Stuttgart-Strasse",
    "Löwenbergweglein",
    "Aescherstrasse",
    "St. Johanns-Rheinweg",
    "Friedrich Oser-Strasse",
    "Buchenstrasse",
    "Beim Wagdenhals",
    "Jacob Burckhardt-Strasse",
    "Dufourstrasse",
    "Innere Margarethenstrasse",
    "Landauerhofweg",
    "Friedmattweglein",
    "Spiegelgasse",
    "St. Alban-Talstrasse",
    "Klingelbergstrasse",
    "Bachofenstrasse",
    "Bettingerweg",
    "Im Heimatland",
    "Badweglein",
    "Palmenstrasse",
    "Kannenfeldpark",
    "Byfangweg",
    "Spiegelbergstrasse",
    "Schlüsselberg",
    "Gellertpark",
    "Kienbergstrasse",
    "Sandgrubenstrasse",
    "Sperrstrasse",
    "Zum Bischofstein",
    "Erlenmattpark",
    "Blotzheimerweg",
    "Jungstrasse",
    "Asconastrasse",
    "Castellioweglein",
    "Mythenstrasse",
    "Webergasse",
    "Wiesenschanzweg",
    "Mühlenberg",
    "Kastanienweg",
    "Schönenbuchstrasse",
    "Andreasplatz",
    "Pruntruterstrasse",
    "Rosentalanlage",
    "Wallstrasse",
    "Predigergässlein",
    "Rittergasse",
    "Gundeldingerstrasse",
    "Jägerstrasse",
    "Reiterstrasse",
    "Flachsländerstrasse",
    "Hermann Albrecht-Strasse",
    "Beuggenweg",
    "Letziplatz",
    "Dammerkirchstrasse",
    "Kirchgasse",
    "Hirschgässlein",
    "Grenzacherstrasse",
    "Amselstrasse",
    "Weisse Gasse",
    "Mailand-Strasse",
    "Mittlere Rheinbrücke",
    "Marschalkenstrasse",
    "Irène Zurkinden-Platz",
    "Kirschblütenweg",
    "Pruntrutermatte",
    "Säckingerstrasse",
    "Reinacherstrasse",
    "Birskopfweglein",
    "Riedbergstrasse",
    "Sissacherstrasse",
    "Iris von Roten-Platz",
    "Kraftstrasse",
    "Peter Rot-Strasse",
    "Steinenberg",
    "Erlenmattweg",
    "Oekolampadstrasse",
    "Buremichelskopfanlage",
    "Johanniterstrasse",
    "Eisweglein",
    "Batterieanlage",
    "Hörnliweglein",
    "Martinskirchplatz",
    "Sandgrubenweglein",
    "Thumringerstrasse",
    "Rheinsprung",
    "Lysbüchelplatz",
    "Solitudepark",
    "In den Klosterreben",
    "Mariasteinstrasse",
    "Lukas Legrand-Strasse",
    "Bauhinweglein",
    "Ryffstrasse",
    "In der Breite",
    "Matthäuskirchplatz",
    "Wolfschluchtweglein",
    "Laufenstrasse",
    "Schwarzwaldallee",
    "Hutgasse",
    "Spiegelhof",
    "Horburgpark",
    "Nadelberg",
    "Bechburgerstrasse",
    "Im Wasenboden",
    "Hammerstrasse",
    "Güterstrasse",
    "De Wette-Strasse",
    "Fürstensteinerstrasse",
    "Urbana Iulia-Strasse",
    "Rigistrasse",
    "Belforterstrasse",
    "Blotzheimerstrasse",
    "Sägergässlein",
    "Rut Keiser-Strasse",
    "Marignanostrasse",
    "Merkuranlage",
    "Muespacherstrasse",
    "Neusatzweglein",
    "Bundesplatz",
    "Auf der Alp",
    "Schanzenstrasse",
    "Im Schmiedenhof",
    "Predigerhofstrasse",
    "Unterer Rheinweg",
    "Röschenzerstrasse",
    "Dora Schmidt-Strasse",
    "Hebelstrasse",
    "Klybeckstrasse",
    "Wien-Strasse",
    "Leonhardsstrasse",
    "Höhenweg",
    "Gustav Wenk-Strasse",
    "Christoph Merian-Park",
    "Schönbeinstrasse",
    "Katja Wulff-Anlage",
    "Wiesendamm-Promenade",
    "Hagenaustrasse",
    "Breitematte",
    "Schwarzpark",
    "Voltaplatz",
    "Sigi von Koeding-Anlage",
    "Maispracherweg",
    "Wielandplatz",
    "Leonhardsstapfelberg",
    "Appenzellerstrasse",
    "J.J. Balmer-Strasse",
    "Henric Petri-Strasse",
    "Kahlstrasse",
    "Wildschutzweg",
    "Gretel Bolliger-Promenade",
    "Lichtstrasse",
    "Kapellenstrasse",
    "Elisabethenschanze",
    "Binningerstrasse",
    "Froburgstrasse",
    "Stücki-Steg",
    "Birsigstrasse",
    "Mönchsbergerstrasse",
    "Theaterstrasse",
    "Schorenweg",
    "Steinenring",
    "Gasstrasse",
    "Singerstrasse",
    "Hirzbodenpark",
    "Claragraben",
    "Pfeffingerstrasse",
    "Pelikanweglein",
    "Gotenwegli",
    "Weiherhofstrasse",
    "Steinenbachgässlein",
    "Wiesenplatz",
    "Lindenhofstrasse",
    "Imbergässlein",
    "Untere Rheingasse",
    "Bürgerkorporationskanzel",
    "Bruderholzhöhe",
    "Salinenstrasse",
    "Hohe Winde-Strasse",
    "Konzertgasse",
    "Weidengasse",
    "Wattstrasse",
    "Hirzbodenweg",
    "Steinenmühlesteg",
    "Hochwaldstrasse",
    "Efringerstrasse",
    "Sevogelplatz",
    "Spalenvorstadt",
    "Im Ettingerhof",
    "Herrengrabenweg",
    "Hersbergerweg",
    "Fischerweg",
    "Helfenbergstrasse",
    "Wiesenallee",
    "Chrischonawegli",
    "Bosenhaldenwegli",
    "Davidsgässchen",
    "Dinkelbergwegli",
    "Eisenbahnweg",
    "Unterm Schellenberg",
    "Wendelinsgasse",
    "Wenkenhaldenweg",
    "Wenkenmattweg",
    "Im Ebacker",
    "Wachtelstrasse",
    "Arnikastrasse",
    "Am Ausserberg",
    "Im Baumgarten",
    "Bäumligasse",
    "Bäumlihofstrasse",
    "Bettingerstrasse",
    "Binsenweg",
    "Bischoffweg",
    "Bluttrainweg",
    "Essigstrasse",
    "Im Singeisenhof",
    "Im finstern Boden",
    "Frühmesswegli",
    "Finsterbodenweg",
    "Garbenstrasse",
    "Gartengasse",
    "Der gerade Weg",
    "Grenzacherstrasse",
    "Grienbodenweg",
    "Gstäderwegli",
    "Gotenwegli",
    "Hinterengeliweg",
    "Hirtenweg",
    "Hirzenstrasse",
    "Höhenstrasse",
    "Holzmühleweg",
    "Hörnliallee",
    "Hubgässchen",
    "Hungerbachweg",
    "Hungerbachhalde",
    "Käppeligasse",
    "Kornfeldstrasse",
    "Oberer Kreuzenweg",
    "Unterer Kreuzenweg",
    "Keltenwegli",
    "Langenlängeweg",
    "Lettackerweg",
    "Lichsenweg",
    "Lörracherstrasse",
    "Lerchengsangweg",
    "Hinter der Mühle",
    "Mühlestiegrain",
    "Mühlemattweg",
    "Mooshaldenweg",
    "Nägeliweg",
    "Nordhaldenweg",
    "Gehrhaldenweg",
    "Petrisweg",
    "Ritterweg",
    "Rudolf Wackernagel-Strasse",
    "Rütiring",
    "Sandreuterweg",
    "Schäferstrasse",
    "Schmiedgasse",
    "Schnitterweg",
    "Seidenmannweg",
    "Sieglinweg",
    "Sonneggstrasse",
    "Sonnenbühlstrasse",
    "Spitalweg",
    "Sternengasse",
    "Am Stich",
    "Stiftsgässchen",
    "Störklingasse",
    "Supperstrasse",
    "Steinenweg",
    "Tiefweg",
    "Talmattwegli",
    "Waltersgrabenweg",
    "Wasserstelzenweg",
    "Wettsteinstrasse",
    "Weilmattweg",
    "Winkelgässchen",
    "Wettsteinanlage",
    "Wiesenmattweg",
    "Am Wiesengriener",
    "Im Wenkenberg",
    "Bannwegli",
    "Auf dem Rücken",
    "Bachgässchen",
    "Binsenackerstrasse",
    "Hörnlistrasse",
    "Horngrabenweg",
    "Mooswegli",
    "Bockrainwegli",
    "Leimgrubenwegli",
    "Bruckwegli",
    "Sperberwegli",
    "Beyelerwegli",
    "Ottiliaweg",
    "Höhenwegli",
    "Buchhaldenweg",
    "Cagliostrostrasse",
    "Hellringwegli",
    "In der Vorstadt",
    "In der Kalkdarre",
    "Buchgasse",
    "Buchholzweg",
    "Bannwegli",
    "Chrischonarain",
    "Obere Dorfstrasse",
    "Der krumme Weg",
    "Hauptstrasse",
    "Inzlingerweg",
    "Im Wenkenberg",
    "Landhausweg",
    "Lindengasse",
    "Mennweg",
    "Riesiwegli",
    "Specklerwegli",
    "Schafrainweg",
    "Talweg",
    "Vierjuchartenweg",
    "Hirzengrabenweg",
    "Im Wildwechsel",
    "Am Bettingerbach",
    "Bärenwegli",
    "Buchsweg",
    "Courvoisierwegli",
    "Geothermiewegli",
    "Hufeisengässchen",
    "Täuferwegli",
    "Ursula Hebel-Wegli",
    "Wolfenfroweg",
    "Zeigerweg",
    "Moosbündtenweg",
    "Salamanderwegli",
    "Dorfplatz",
    "Otto Wenk-Platz",
    "Kaiserweg",
    "Ziegelgrubenweg",
    "Lothringerstrasse",
    "Neubadstrasse",
    "Turnerstrasse",
    "Solothurnerstrasse",
    "Obwaldnerstrasse",
    "Adlerstrasse",
    "Buschweilerweg",
    "Kaltbrunnen-Promenade",
    "Maja Sacher-Platz",
    "Nenzlingerstrasse",
    "Rauracherwegli",
    "Hermann Suter-Strasse",
    "Sundgauerstrasse",
    "Redingstrasse",
    "Duggingerhof",
    "Murtengasse",
    "Klingentalweglein",
    "Theodor Herzl-Anlage",
    "Wyhlenweglein",
    "Erlenmattplatz",
    "Totentanz",
    "Südquaistrasse",
    "In den Klostermatten",
    "Weilerweg",
    "Altrheinweg",
    "Therwilerstrasse",
    "Meltingerstrasse",
    "Krachenrainweglein",
    "Galgenhügel-Promenade",
    "Kluserstrasse",
    "Beim Buremichelskopf",
    "Theodorskirchplatz",
    "Sarnerstrasse",
    "Erlenparksteg",
    "Albert Schweitzer-Strasse",
    "Volkensbergerstrasse",
    "Wettsteinplatz",
    "Hans Huber-Strasse",
    "Herrenweg",
    "Engelgasse",
    "Rheinländerstrasse",
    "Brennerstrasse",
    "Burgunderstrasse",
    "Achilles Bischoff-Strasse",
    "Nachtkerzenweg",
    "Haltingerstrasse",
    "Rheinweilerweg",
    "Kirschgartenstrasse",
    "Hegenheimerstrasse",
    "Am Bahndamm",
    "Leonhardsberg",
    "Magnolienpark",
    "Gotthelfplatz",
    "Kronenplatz",
    "Erlenstrasse",
    "Bürenfluhstrasse",
    "Edisonstrasse",
    "Im Rankhof",
    "Margarethenstich",
    "Vogesenplatz",
    "Erlkönigweg",
    "Andlauerstrasse",
    "Kunigunde-Platz",
    "Wibrandis Rosenblatt-Weg",
    "Rodersdorferstrasse",
    "Claramatte",
    "Rheinfelderstrasse",
    "St. Johanns-Park",
    "Münzgasse",
    "Friedrichstrasse",
    "Eichhornstrasse",
    "Rixheimerstrasse",
    "Pfirteranlage",
    "Schaffhauserrheinweg",
    "Hechtliacker",
    "Redingbrücke",
    "Fringeliweglein",
    "Bonergasse",
    "Zoo-Parkplatz",
    "Ahornstrasse",
    "Belchenstrasse",
    "Schöllenenstrasse",
    "Igelweglein",
    "Brunnmattstrasse",
    "Maiengasse",
    "Schneidergasse",
    "Ziegelstrasse",
    "Kembserweg",
    "Altkircherstrasse",
    "Peter Merian-Weg",
    "Münsterplatz",
    "Rodrisstrasse",
    "Mülhauserstrasse",
    "Schützenmattstrasse",
    "Hofweglein",
    "Johanniterbrücke",
    "Weinlagerstrasse",
    "Im Heimgarten",
    "Lehenmattstrasse",
    "Chrischonastrasse",
    "Luftgässlein",
    "Im Margarethental",
    "Löwenbergstrasse",
    "Auf dem Hummel",
    "Hechtweg",
    "Uferstrasse",
    "Realpstrasse",
    "Airoloweglein",
    "Elisabethen-Passage",
    "Jakobsbergerweglein",
    "Lohnhofgässlein",
    "Dreihäusernweglein",
    "Steinenschanze",
    "Felsplattenstrasse",
    "Hangweglein",
    "Bahnhof-Passerelle",
    "Schnabelgasse",
    "Zum Hilsenstein",
    "Fringelistrasse",
    "Pilgerstrasse",
    "Birskopfsteg",
    "Theodor Herzl-Strasse",
    "Feierabendstrasse",
    "Falkensteineranlage",
    "Rufacherstrasse",
    "Pestalozzistrasse",
    "Antilopenweg",
    "Kartausgasse",
    "St. Johanns-Platz",
    "Lyon-Strasse",
    "Eisenbahnweg",
    "Bruderholzallee",
    "Dorenbachviadukt",
    "Scheltenweglein",
    "Scheltenstrasse",
    "Gellertweglein",
    "Hardrain",
    "Zähringerstrasse",
    "Baldeggerstrasse",
    "St. Alban-Anlage",
    "Schlachthofstrasse",
    "Kaufhausgasse",
    "Singerweg",
    "Weissensteinstrasse",
    "Steinbühlplatz",
    "St. Alban-Rheinweg",
    "Zu den drei Linden",
    "Hirzbrunnenstrasse",
    "Sustenstrasse",
    "Giebenacherweg",
    "Spalentorweg",
    "Schulgasse",
    "Hochbergerplatz",
    "Liestaleranlage",
    "Seltisbergerweglein",
    "Bläsiring",
    "Ringgässlein",
    "Wollbacherstrasse",
    "Tschudi-Park",
    "Schliengerweg",
    "Allschwilerstrasse",
    "Sperrweglein",
    "Dorenbach-Promenade",
    "Oltingerstrasse",
    "Dreirosenstrasse",
    "Glockengasse",
    "Schafgässlein",
    "Buschweilerweglein",
    "Wartenbergstrasse",
    "Kaysersbergerstrasse",
    "Gottfried Keller-Strasse",
    "Voltamatte",
    "Schlachthofbrücke",
    "Römergasse",
    "Markgräflerstrasse",
    "Hebelschanze",
    "Birseckweglein",
    "Passwangsteg",
    "Hagentalerstrasse",
    "Offenburgerstrasse",
    "Fechterweglein",
    "Helli Stehle-Weg",
    "Anwilerstrasse",
    "Wildensteinerstrasse",
    "Schäublinweglein",
    "Landauerstrasse",
    "Scherkesselweg",
    "Urs Graf-Strasse",
    "Starenweglein",
    "Föhrenstrasse",
    "Vogelsangstrasse",
    "Bonfolstrasse",
    "Dolderweg",
    "Bollwerk-Promenade",
    "Im Sesselacker",
    "Max Kämpf-Platz",
    "Tiefenbodenweglein",
    "Utengasse",
    "Mostackerstrasse",
    "Unterer Heuberg",
    "Auberg",
    "Lichtnelkenweg",
    "Landskronstrasse",
    "Kleinhüningeranlage",
    "Riehentorstrasse",
    "Elsässerstrasse",
    "Theatergässlein",
    "Pfeffergässlein",
    "Erikastrasse",
    "Jakobsbergerholzweg",
    "Paracelsusstrasse",
    "Grenzstrasse",
    "Pfeffelstrasse",
    "Stadionstrasse",
    "Wiesensteg",
    "Grienstrasse",
    "Liesbergermatte",
    "Paradieshofstrasse",
    "Delsbergerallee",
    "Holbeinplatz",
    "Röttelerstrasse",
    "Bläsianlage",
    "Mathilde Paravicini-Strasse",
    "Sempacherstrasse",
    "Stadthausgasse",
    "Bristenweg",
    "Theaterplatz",
    "Burgweg",
    "Egliseestrasse",
    "Im Spitzacker",
    "Grenzacher-Promenade",
    "Dreirosenanlage",
    "Wasserturm-Promenade",
    "Schlossgasse",
    "Drosselstrasse",
    "Sevogelstrasse",
    "Am Krayenrain",
    "Liesbergerstrasse",
    "Ulmenweglein",
    "Finkenweg",
    "Kohlenberggasse",
    "Ramsteinerstrasse",
    "Rheinschanze",
    "Im Burgfelderhof",
    "Prag-Strasse",
    "Gartenstrasse",
    "Habsburgerstrasse",
    "Vogel Gryff-Gässli",
    "Untere Rebgasse",
    "Andreas Heusler-Strasse",
    "St. Galler-Ring",
    "Karpfenweg",
    "Tannenfluhweg",
    "Pfarrgasse",
    "Sternenbergerstrasse",
    "Beinwilerstrasse",
    "Gilgenbergerstrasse",
    "Birseckstrasse",
    "Fahnengässlein",
    "Julia Gauss-Strasse",
    "Steinenstapfelberg",
    "Birsfelderstrasse",
    "Thiersteinerallee",
    "Hagenbachstrasse",
    "St. Jakobs-Weglein",
    "Schützengraben",
    "Homburgerstrasse",
    "Kleinriehen-Promenade",
    "Clarastrasse",
    "Kornhausgasse",
    "Kaltbrunnenstrasse",
    "Magdenweglein",
    "Neudorfstrasse",
    "Im Holeeletten",
    "Malzgasse",
    "Sesselackerweglein",
    "Furkastrasse",
    "Margarethenstrasse",
    "Gerbergasse",
    "Rümmingerstrasse",
    "Bruderholzrain",
    "Backstubenweg",
    "Kasernenstrasse",
    "Otterbachweg",
    "Hirzbrunnen-Promenade",
    "Grimselstrasse",
    "Birsig-Durchgang",
    "Glaserbergstrasse",
    "Rheingasse",
    "Zwingerstrasse",
    "Daniel Fechter-Promenade",
    "Beim Goldenen Löwen",
    "Prattelerstrasse",
    "Wiesenkreisel",
    "Wilhelm Klein-Strasse",
    "Lehenmattweg",
    "Margarethenbrücke",
    "Binzenstrasse",
    "Erlenparkweg",
    "Forellenweg",
    "Klybeckplatz",
    "Rosentalstrasse",
    "Knöringerstrasse",
    "Marignanoweglein",
    "Missionsstrasse",
    "Sägebergweglein",
    "Dittingerstrasse",
    "Eulerstrasse",
    "Tüllingerstrasse",
    "Marktplatz",
    "Sonnenbergstrasse",
    "Lenzgasse",
    "Giesslipark",
    "Martinsgasse",
    "Rütimeyerplatz",
    "Rütimeyerstrasse",
    "Aeneas Silvius-Strasse",
    "Wintersingerweglein",
    "Drei König-Weglein",
    "Dornacherstrasse",
    "Rotterdam-Strasse",
    "Rudolfstrasse",
    "Heuwaage",
    "Rosenfeldpark",
    "Rosenauweglein",
    "Friedhofgasse",
    "Oscar Frey-Strasse",
    "Sonnenweg",
    "Petersplatz",
    "Ochsengasse",
    "Hermann Hesse-Platz",
    "Kleinriehenstrasse",
    "Peter Ochs-Strasse",
    "Ackermätteli",
    "Küchengasse",
    "Attila-Passage",
    "Luzernerring",
    "Sennheimerstrasse",
    "Casinostrasse",
    "Auf der Lyss",
    "Fatiostrasse",
    "Holderstrasse",
    "In den Schorenmatten",
    "Tiergartenrain",
    "Bedrettostrasse",
    "Benkenanlage",
    "Tangentenweg",
    "Rümelins-Passage",
    "Gempenfluhweglein",
    "Schopfheimerstrasse",
    "Ormalingerweg",
    "Gemsberg",
    "St. Johanns-Vorstadt",
    "Kandererstrasse",
    "Hermann Kinkelin-Strasse",
    "Gerberberglein",
    "Brombacherstrasse",
    "Bellinzonaweglein",
    "Schillerstrasse",
    "Heuberg",
    "Eidgenossenweg",
    "Bordeaux-Strasse",
    "Speiserstrasse",
    "Neuweilerstrasse",
    "Immengasse",
    "Bollweilerstrasse",
    "Walkeweg",
    "Falkensteinerstrasse",
    "Ueli-Gässli",
    "Hofstetterstrasse",
    "Eisenbahnbrücke",
    "Lohweg",
    "Oekolampadmatte",
    "Rebweg",
    "Rämelstrasse",
    "Leonhardsgraben",
    "Fabrikstrasse",
    "Zur Gempenfluh",
    "Drahtzugstrasse",
    "Schleifenbergstrasse",
    "Bändelgasse",
    "Eichhornweglein",
    "Schalerstrasse",
    "Hunnenstrasse",
    "Nachtigallenwäldeli",
    "Fasanenstrasse",
    "Falknerstrasse",
    "Emilie Louise Frey-Strasse",
    "Bäumleingasse",
    "Tödistrasse",
    "Sonnenbergweglein",
    "Fischmarkt",
    "Schauenburgerstrasse",
    "Tellstrasse",
    "Gellertstrasse",
    "Ackerstrasse",
    "Gundeli-Passerelle",
    "Fröschgasse",
    "Birkenstrasse",
    "Barfüssergasse",
    "Breisacherstrasse",
    "Bahnweglein",
    "Chrischonaweg",
    "Dinkelbergstrasse",
    "Hutzlenweg",
    "Im Rumpel",
    "Eglingerweg",
    "Obere Wenkenhofstrasse",
    "Im Linsberg",
    "Untere Weid",
    "Heinrich Heusser-Weg",
    "In der Au",
    "Auhaldenweg",
    "Albert Oeri-Strasse",
    "Baselstrasse",
    "Aeussere Baselstrasse",
    "Bäumliweg",
    "Bosenhaldenweg",
    "Breitmattenweg",
    "Brühlmattweg",
    "Brünnlirain",
    "Brunnwegli",
    "Burckhardtgässchen",
    "Auf der Bischoffhöhe",
    "Erlensträsschen",
    "Eulenweg",
    "Friedhofweg",
    "Fürfelderstrasse",
    "Gänshaldenweg",
    "Gatternweg",
    "Gotenstrasse",
    "In den Habermatten",
    "Hackbergstrasse",
    "Am Hang",
    "Haselrain",
    "Heissensteinweg",
    "Hinter Gärten",
    "Im Hirshalm",
    "Hohlweg",
    "Habermarkweg",
    "Hüslimattweg",
    "Haldenweg",
    "Kilchgässli",
    "Kohlistieg",
    "Krämergässchen",
    "Lachenwegli",
    "Lachenweg",
    "Lamperstalweg",
    "Lampiweg",
    "Maienbühlsträsschen",
    "Maienbühlweg",
    "Martinsrain",
    "Meierweg",
    "Mohrhaldenstrasse",
    "Morystrasse",
    "Im Niederholzboden",
    "Niederholzstrasse",
    "Niederholzrainweg",
    "Neumattenhofwegli",
    "Oberdorfstrasse",
    "Rauracherwegli",
    "Rebenstrasse",
    "Rheintalweg",
    "Roggenstrasse",
    "Rotengrabenweg",
    "Rankweg",
    "Schiessrain",
    "Schlipfweg",
    "Schützengasse",
    "Stellimattweg",
    "Stettengrabenweg",
    "Stettenweg",
    "Spittlerwegli",
    "Sonnenhaldenwegli",
    "Talweg",
    "Talmattstrasse",
    "Vormbergweg",
    "Webergässchen",
    "Haldenwegli",
    "Landauerwegli",
    "Moosrainwegli",
    "Niederholzbodenwegli",
    "Bachtelenwegli",
    "Brunnstubenwegli",
    "Spechtweg",
    "Hunnenwegli",
    "Bei der Lehmgrube",
    "Beim Waschhaus",
    "Am alten Teich",
    "Brohegasse",
    "Brunnengasse",
    "Buchweg",
    "Bückenweg",
    "Bückenwegli",
    "Chrischonatalweg",
    "Fünfeichenweg",
    "Herrenhagweg",
    "Habermarkweg",
    "Jägerweg",
    "In der Leimgrube",
    "Mattenwegli",
    "Rainweg",
    "Riesiweg",
    "Steinengasse",
    "Stelliweg",
    "Talmattstrasse",
    "Totenweg",
    "Weingärtenweg",
    "Wyhlenweg",
    "Winkelweg",
    "Im nassen Grund",
    "Kaiserweg",
    "Anna Fischer-Wegli",
    "Auf der Burg",
    "Dattenlochweg",
    "Eliaswegli",
    "Gertrud Späth-Wegli",
    "Gerwikweg",
    "Herrenwaldweg",
    "Im Bettingertäli",
    "In der Muelte",
    "Odalsindawegli",
    "Kornfeldwegli",
    "Kirchplatz",
    "Wiesentunnel",
    "Fuchswegli",
    "Chrischonatalweg",
    "Wolfschlucht-Promenade",
    "Bad. Bahnhof-Passage",
    "Eggfluhstrasse",
    "Klingental",
    "Schönaustrasse",
    "Herbergsgasse",
    "Buremichelskopf-Promenade",
    "Sternengasse",
    "Bartenheimerstrasse",
    "Petersgasse",
    "Freiburgerstrasse",
    "Wittlingerweglein",
    "Lindenweg",
    "Hundsbuckelweglein",
    "Peter Merian-Strasse",
    "Gertrud Spiess-Strasse",
    "Erlenmattstrasse",
    "Luftmattstrasse",
    "Kannenfeldstrasse",
    "Riehenstrasse",
    "Faidostrasse",
    "Gempenstrasse",
    "Birmannsgasse",
    "Claramattweg",
    "Spitalstrasse",
    "Luzernerring-Brücke",
    "Erdbeergraben",
    "Mülhauserweglein",
    "Wettsteinallee",
    "Friedrich Miescher-Weg",
    "Im Zimmerhof",
    "Viaduktstrasse",
    "Florastrasse",
    "Waldshuterstrasse",
    "Brunngässlein",
    "Reservoirstrasse",
    "Säntisstrasse",
    "Trudi Gerster-Anlage",
    "Magdenstrasse",
    "Waldighoferstrasse",
    "Lange Gasse",
    "Riehenteichstrasse",
    "Thiersteinersteg",
    "Seltisbergerstrasse",
    "Gotthelfstrasse",
    "Mauerstrasse",
    "Nagelfluhweglein",
    "Sulzerstrasse",
    "Allschwilerplatz",
    "Rennweg",
    "Benkenstrasse",
    "Colmarerstrasse",
    "Spalen-Durchgang",
    "Im Lohnhof",
    "Wintersingerweg",
    "Lachenalweglein",
    "Birskopf",
    "Rührbergerstrasse",
    "Frankfurt-Strasse",
    "Eisengasse",
    "Angensteinerstrasse",
    "Blauenstrasse",
    "Roggenburgstrasse",
    "Gansgässlein",
    "Dörnliweg",
    "Elsternweg",
    "Weilstrasse",
    "Weilteichweg",
    "Weizenstrasse",
    "Untere Wenkenhofstrasse",
    "Bärlauchwegli",
    "Auf den Stellimatten",
    "Keltenweg",
    "Dorenbachstrasse",
    "Artelweg",
    "An der Auhalde",
    "Auweg",
    "Ausserbergweg",
    "Bachtelenweg",
    "Bahnhofstrasse",
    "Stapfelwegli",
    "Auwegli",
    "Bettingerweg",
    "Bierkellerweg",
    "Burgstrasse",
    "Im Esterli",
    "Esterliweg",
    "Obere Weid",
    "Im Gehracker",
    "Gehrhalde",
    "Gerstenweg",
    "Grasserweg",
    "Grendelgasse",
    "Grenzacherweg",
    "Gstaltenrainweg",
    "Gänshaldenwegli",
    "Hellring",
    "Helvetierstrasse",
    "Im Höfli",
    "Hungerbachwegli",
    "Inzlingerstrasse",
    "Immenbachstrasse",
    "Kettenackerweg",
    "Kilchgrundstrasse",
    "Kirchstrasse",
    "Der krumme Weg",
    "Langoldshaldenweg",
    "Leimgrubenweg",
    "Lärchenweg",
    "Moosweg",
    "Mühlestiegstrasse",
    "In den Neumatten",
    "Nollenbrunnenweg",
    "Paradiesstrasse",
    "Pfaffenlohweg",
    "Rainallee",
    "Rauracherstrasse",
    "Römerfeldstrasse",
    "Rössligasse",
    "Rüchligweg",
    "Rüdinstrasse",
    "Schlossgasse",
    "Schopfgässchen",
    "Schützenrainweg",
    "Siegwaldweg",
    "Sperberweg",
    "Spittelmattweg",
    "Steingrubenweg",
    "Stettenlochweg",
    "Steinbrecheweg",
    "Unholzgasse",
    "Vierjuchartenweg",
    "Wenkenstrasse",
    "Hinterwenkenweg",
    "Wiesendamm-Promenade",
    "Weihersteg",
    "Ziegelhüttenwegli",
    "Bäumlihofwegli",
    "Bückliwegli",
    "Haidweg",
    "Linsbergweg",
    "Bischoffwegli",
    "Brühlweg",
    "Im Hinterengeli",
    "Bockrainweg",
    "Arnold Hof-Wegli",
    "Im Glögglihof",
    "Aegelgrabenweg",
    "Auf der Ebene",
    "Im Krebstaschenboden",
    "In der Hell",
    "Am Mühleteich",
    "Anstaltsweg",
    "Ausserbergweg",
    "Baiergasse",
    "Biräckerweg",
    "Büntenweg",
    "Britzigerweg",
    "Chrischonabodenweg",
    "Girenhaldenweg",
    "An der Hand",
    "Hohe Strasse",
    "Habermarkwegli",
    "Lauberweg",
    "Lenzenweg",
    "Linsbergweg",
    "Petersgasse",
    "Silberbergweg",
    "Im Speckler",
    "Vormbergweg",
    "Wyhlengrabenweg",
    "Horngrabenweg",
    "Reubergweg",
    "Rütenenweg",
    "Ebowegli",
    "In der Eisernen Hand",
    "Stumpgässchen",
    "Erlensteg",
    "Erlenweg",
    "Stettenwegli",
    "Anna Maria Wettstein-Wegli",
    "Unterer Haidweg",
    "Reubergweg",
    "Zollfreie Strasse",
    "Wackernagel-Park",
    "Lindenplatz",
    "Fuchsweg",
    "Mohrhaldenanlage",
    "Gewerbeareal im Rüchlig",
    "Auf dem Wolf",
    "Salmgässli",
    "Largitzenstrasse",
    "Hüningerstrasse",
    "Horburgstrasse",
    "Starenstrasse",
    "Greifengasse",
    "Strassburgerallee",
    "Steinbühlallee",
    "Hummelweglein",
    "Giornicostrasse",
    "Burgfelderstrasse",
    "Alemannengasse",
    "Schertlingasse",
    "Hafenstrasse",
    "Ingelsteinweg",
    "Wanderstrasse",
    "Im Grenzacherhof",
    "Claraplatz",
    "Hohe Winde-Steg",
    "Olsbergerweg",
    "Centralbahn-Passage",
    "Emanuel Büchel-Strasse",
    "Clarahofweg",
    "Austrasse",
    "Riburgstrasse",
    "Winkelriedplatz",
    "Theater-Passage",
    "Klostergasse",
    "Steinentorstrasse",
    "Streitgasse",
    "Elisabethenanlage",
    "Stapfelberg",
    "Chrischonaweglein",
    "Metzerstrasse",
    "Solitude-Promenade",
    "Karl Barth-Platz",
    "Peterskirchplatz",
    "Brüglingerstrasse",
    "Blauensteinerstrasse",
    "Bachlettenstrasse",
    "Bleichestrasse",
    "St. Alban-Berg",
    "Landauerwegli",
    "Bellinzonastrasse",
    "Klingentalstrasse",
    "Dachsfelderstrasse",
    "Zwölfjuchartenweglein",
    "St. Alban-Vorstadt",
    "Karl Jaspers-Allee",
    "Paul Sacher-Anlage",
    "Picassoplatz",
    "Amerbachstrasse",
    "Lindenberg",
    "Erstfeldstrasse",
    "Joh.Jak. Spreng-Gässlein",
    "Fasnachtsgasse",
    "Kohlenberg",
    "Beuggenstrasse",
    "Theodorsgraben",
    "Schwarzwaldstrasse",
    "Hochstrasse",
    "Bürenfluhweglein",
    "Aeschenplatz",
    "Pfalz",
    "Eimeldingerweg",
    "Welschmattstrasse",
    "Birsig-Parkplatz",
    "Waldeckstrasse",
    "Davidsbodenstrasse",
    "Leimenstrasse",
    "Münsterberg",
    "Gerbergässlein",
    "Krachenrain",
    "Schlangenweglein",
    "Davidsbodenweglein",
    "Giessliweg",
    "Christoph Merian-Platz",
    "Markircherstrasse",
    "Gundeldingerrain",
    "Flughafenstrasse",
    "Lysbüchelstrasse",
    "Ensisheimerstrasse",
    "Im Margarethenletten",
    "Marktgasse",
    "Lerchenstrasse",
    "Stänzlergasse",
    "Nidwaldnerstrasse",
    "Wilhelm His-Strasse",
    "Unter der Batterie",
    "Beim Wettsteinhäuschen",
    "Heumattstrasse",
    "Unterer Batterieweg",
    "Beckenstrasse",
    "Mittlere Strasse",
    "Markthallenbrücke",
    "Bärenfelserstrasse",
    "Neuhausstrasse",
    "Meret Oppenheim-Strasse",
    "Centralbahnplatz",
    "Wasensträsschen",
    "Bäumlihofstrasse",
    "Bellingerweg",
    "Hochbergerstrasse",
    "Oetlingerstrasse",
    "Grünpfahlgasse",
    "Fritz Hauser-Promenade",
    "Klosterfiechtenweg",
    "Grosspeteranlage",
    "Arabienstrasse",
    "Wettsteinbrücke",
    "Jakobsbergerstrasse",
    "Ingelsteinweglein",
    "Schönmattstrasse",
    "Hasenmattstrasse",
    "Weiherweg",
    "Hexenweglein",
    "Häsingerstrasse",
    "Eugen Wullschleger-Strasse",
    "Signalstrasse",
    "Thannerstrasse",
    "Bannwartweg",
    "Elsässerrheinweg",
    "Bergalingerstrasse",
    "Klingnaustrasse",
    "Schifflände",
    "Schwörstadterstrasse",
    "Vesalgasse",
    "Passwangstrasse",
    "Frobenstrasse",
    "Barfüsserplatz",
    "Wintergasse",
    "Lautengartenstrasse",
    "Kleinhüningerstrasse",
    "Kabelstrasse",
    "Schützenmattpark",
    "Schweizergasse",
    "Sängergasse",
    "Reservoirweglein",
    "In den Ziegelhöfen",
    "Herbstgasse",
    "Centralbahnstrasse",
    "Martinsgässlein",
    "Kannenfeldweglein",
    "Türkheimerstrasse",
    "Hasenmattweglein",
    "Airolostrasse",
    "Zürcherstrasse",
    "Reichensteinerstrasse",
    "Hardstrasse",
    "Gotthardstrasse",
    "Pirolweg",
    "Leonhardskirchplatz",
    "Münsterfähribödeli",
    "Schönenbergstrasse",
    "General Guisan-Strasse",
    "Arlesheimerstrasse",
    "Nasenweg",
    "Dreirosenbrücke",
    "Freiburgersteg",
    "Pelikanweg",
    "Beim Wasserturm",
    "Tanzgässlein",
    "Forum",
    "Im Westfeld",
    "Sommergasse",
    "Westquaistrasse",
    "Grosspeterstrasse",
    "Leimgrubenweg",
    "Hirzbrunnenschanze",
    "Müllheimerstrasse",
    "Im Rheinacker",
    "Dorfstrasse",
    "Innerer Egliseeweg",
    "Eiserner Steg",
    "Friedrich Miescher-Strasse",
    "Im Witterswilerhof",
    "Steinengraben",
    "Bachgraben-Promenade",
    "Rütlistrasse",
    "Septerstrasse",
    "Schäfermatte",
    "Feldbergstrasse",
    "Elftausendjungfern-Gässlein",
    "Krakau-Strasse",
    "Emil Angst-Strasse",
    "Brantgasse",
    "St. Johanns-Parkweg",
    "Nufenenstrasse",
    "Matthäusstrasse",
    "Rappenbodenweg-Promenade",
    "Schönenbergweglein",
    "Eptingerstrasse",
    "Socinstrasse",
    "Meisengasse",
    "St. Jakobs-Strasse",
    "Farnsburgerstrasse",
    "Brüssel-Strasse",
    "Wasserstrasse",
    "Blumengasse",
    "Davidsrain",
    "Bärschwilerstrasse",
    "St. Alban-Graben",
    "Klingentalgraben",
    "Heinrichsgasse",
    "Rebgasse",
    "Bundesstrasse",
    "Bündnerstrasse",
    "Rümelinsplatz",
    "Oberwilerstrasse",
    "Pfluggässlein",
    "Akazienweg",
    "Kannenfeldplatz",
    "Neuensteinerstrasse",
    "Archivgässlein",
    "Ob der Wanne",
    "Elisabethenstrasse",
    "Petersgraben",
    "Uhlandstrasse",
    "Neusatzsteg",
    "Spalengraben",
    "Eiszeitenweg",
    "Beckenweg",
    "Paulusgasse",
    "Rudolf Steiner-Weg",
    "Inselstrasse",
    "Teichgässlein",
    "Thiersteinerrain",
    "Saint-Louis-Park",
    "Post-Passage",
    "Schäferweg",
    "Blochmonterstrasse",
    "Rankweglein",
    "Leuengasse",
    "Oberer Batterieweg",
    "Morgartenring",
    "Mühlegraben",
    "Parkweg",
    "Tellplatz",
    "Itelpfad",
    "Lützelstrasse",
    "Vogesenstrasse",
    "Steinbühlweg",
    "Badenstrasse",
    "Heuwaage-Viadukt",
    "Rosshofgasse",
    "Friedlingerstrasse",
    "Thiersteinerweglein",
    "Wiesenstrasse",
    "St. Alban-Kirchrain",
    "Kohlenstrasse",
    "Vogelsangweglein",
    "Rümelinbachweg",
    "Holbeinstrasse",
    "Aeschengraben",
    "Messeplatz",
    "Spalenring",
    "Nonnenweg",
    "Beim Letziturm",
    "Im Triangel",
    "Hirzbrunnenallee",
    "Tramweglein",
    "Michelbacherstrasse",
    "St. Johanns-Ring",
    "Kastelstrasse",
    "Muttenzerweg",
    "Erasmusplatz",
    "Zeglingerweg",
    "Hauserweglein",
    "Rankstrasse",
    "Voltastrasse",
    "Niklaus von Flüe-Strasse",
    "Göschenenstrasse",
    "Hasenberg",
    "Goldbachweg",
    "Bruderholzstrasse",
    "Guisan-Promenade",
    "Wild Ma-Gässli",
    "Näfelserstrasse",
    "Batterieweglein",
    "Keltentreppe",
    "Steinenvorstadt",
    "Baumgartenweg",
    "St. Albantor-Anlage",
    "Reusstrasse",
    "Sattelgasse",
    "Meret Oppenheim-Platz",
    "Trillengässlein",
    "Mattenstrasse",
    "Im Surinam",
    "Lothringerplatz",
    "Anne Frank-Platz",
    "Helvetiaplatz",
    "Peter Merian-Brücke",
    "Laufenburgerstrasse",
    "Tessinstrasse",
    "Novarastrasse",
    "Münchensteinerstrasse",
    "Augustinergasse",
    "Grimselweglein",
    "Laupenring",
    "Badenweilerstrasse",
    "Hölleweglein",
    "Im langen Loh",
    "Jurastrasse",
    "Birsstrasse",
    "Bungestrasse",
    "Reverenzgässlein",
    "Theodorsgrabenanlage",
    "Giornico-Promenade",
    "St. Alban-Tal",
    "Nauenstrasse",
    "Klosterberg",
    "Rappoltshof",
    "Schwarzwaldbrücke",
    "Rosengartenweg",
    "C.F. Meyer-Strasse",
    "Hiltalingerstrasse",
    "Färberstrasse",
    "Cécile Ines Loos-Anlage",
    "Fritz Hauser-Strasse",
    "Gärtnerstrasse",
    "Horburgplatz",
    "Blumenrain",
    "Oberer Rheinweg",
    "Oserweglein",
    "Entenweidstrasse",
    "Bernerring",
    "Kanonengasse",
    "Rüdengasse",
    "Holeestrasse",
    "Riehenring",
    "Stöberstrasse",
    "Spittelmattweg",
    "Bernoullistrasse",
    "Eichenstrasse",
    "Am Bachgraben",
    "Wasgenring",
    "Arbedostrasse",
    "Zeglingerweglein",
    "Isteinerstrasse",
    "Freie Strasse",
    "Batterie",
    "Fäschenweglein",
    "Stiftsgasse",
    "Steinentorberg",
    "Bättwilerstrasse",
    "Burgfelderplatz",
    "An der hohlen Gasse",
    "Rastatterstrasse",
}
