FEMALE_NAMES_NOT_ENDING_IN_A = {
    "A. Barb.",
    "A. Elis.",
    "A. Elisab.",
    "A. Kath.",
    "A. Marg.",
    "Adele",
    "Adeline",
    "Adèle",
    "Agathe",
    "Agn.",
    "Agnes",
    "Albertine",
    "Alice",
    "Aline",
    "Amalie",
    "Amelie",
    "Amélie",
    "Anna Barb.",
    "Anna Elis.",
    "Anna Elisab.",
    "Anna Elisabeth",
    "Anna Elise",
    "Anna Kath.",
    "Anna M.",
    "Anna Magd.",
    "Anna Marg.",
    "Anna Marie",
    "Antoinette",
    "Antonie",
    "Augustine",
    "Babette",
    "Barb.",
    "Betty",
    "Blanche",
    "Carol.",
    "Caroline",
    "Cath.",
    "Cecile",
    "Charlotte",
    "Christiane",
    "Christine",
    "Clementine",
    "Clotilde",
    "Cäc.",
    "Cäcilie",
    "Cécile",
    "Célestine",
    "Doroth.",
    "Edith",
    "Eleonore",
    "Elis.",
    "Elisab.",
    "Elisab. Part.",
    "Elisabeth",
    "Elise",
    "Elsbeth",
    "Else",
    "Emile",
    "Emilie",
    "Emma Luise",
    "Emmy",
    "Ernest",
    "Ernestine",
    "Esther",
    "Eugenie",
    "Fanny",
    "Felicitas",
    "Florentine",
    "Florine",
    "Friederike",
    "Georgette",
    "Georgine",
    "Gertr.",
    "Gertrud",
    "Gertrude",
    "Hedwig",
    "Helene",
    "Henriette",
    "Hermine",
    "Hortense",
    "Hélène",
    "Jakobine",
    "Jeanne",
    "Jeannette",
    "Jenny",
    "Josefine",
    "Josephine",
    "Judith",
    "Juliane",
    "Julie",
    "Juliette",
    "Justine",
    "Karol",
    "Karol.",
    "Karoline",
    "Kath.",
    "Kath. Barb.",
    "Kath. Elis.",
    "Kath. Elisab.",
    "Kath. Part.",
    "Kath. Tagl.",
    "Kathar.",
    "Katharine",
    "Kunigunde",
    "Laure",
    "Leonie",
    "Leontine",
    "Leopoldine",
    "Lily",
    "Lis.",
    "Lisette",
    "Louise",
    "Lucie",
    "Luise",
    "Léonie",
    "M. Elis.",
    "M. Elisab.",
    "M. Jos.",
    "M. Kath.",
    "M. Luise",
    "M. Magd.",
    "M. Marg.",
    "M. Ros.",
    "Magd.",
    "Magdal.",
    "Marg.",
    "Marg. Elis.",
    "Margar.",
    "Margarete",
    "Marguerite",
    "Maria A.",
    "Maria Barb.",
    "Maria Elis.",
    "Maria Elisab.",
    "Maria Elisabeth",
    "Maria Jos.",
    "Maria Karol.",
    "Maria Kath.",
    "Maria Louise",
    "Maria Luise",
    "Maria Magd.",
    "Maria Marg.",
    "Maria Urs.",
    "Marianne",
    "Marie",
    "Marie Elisab.",
    "Marie Luise",
    "Mathilde",
    "Melanie",
    "Ottilie",
    "Ottlie",
    "Pauline",
    "Philippine",
    "Philomene",
    "Regine",
    "Ros.",
    "Ros. Kath.",
    "Ros. Marg.",
    "Rosalie",
    "Rose",
    "Rosette",
    "Rosine",
    "Sab.",
    "Salome",
    "Sarah",
    "Seline",
    "Seraf.",
    "Seraph.",
    "Sofie",
    "Soph.",
    "Sophie",
    "Sophie Elisab.",
    "Stefanie",
    "Stephanie",
    "Sus.",
    "Sus. Kath.",
    "Susanne",
    "Suzanne",
    "Ther.",
    "Theres",
    "Theres.",
    "Therese",
    "Valerie",
    "Virginie",
    "Wilh.",
    "Wilhelmine",
    "Yvonne",
}
