UNALLOWED_STRINGS = {
    "$\\S$ text ",
    "text ",
    " text",
    " f ",
    "fractext",
    " fractext",
    "fractext ",
    "fracmathfrakfmathfrakf",
    "fracmath",
    " fracmath",
    "fracmath ",
    "fracmathfrakf",
    "mathfrak",
    "frac",
    " frac",
    "frac ",
    "frakf",
    " frakf",
    "frakf ",
    "bullet",
    "therefore",
    "otimes",
    "oplus",
    "odot",
    "|",
    "½",
    "circ",
    "Dagger",
    "dagger",
    "Φ",
    "φ",
    "ψ",
    "α",
    "@",
    "diamond",
    "()",
}
UNALLOWED_AT_START_OF_STRING = {"of ", "ž", "Š", "ß", ")"}
