JOBS_SUBSTITUTION_MAP = {
    "arb.": "Arbeiter",
    "arb. scb.": "Arbeiter schick",
    "archit.": "architekt",
    "aufs.": "aufsicht",
    "aufsr.": "aufseher",
    "bandfabrikt.": "Bandfabrikant",
    "banq.": "Bankier",
    "baumstr.": "Baumschneider",
    "bes.": "bestatter",
    "bierbr.": "bierbrauer",
    "brieftr.": "briefträger",
    "bäckermstr.": "Bäckermeister",
    "dr.": "Doktor",
    "eidg": "Eidgenössischer",
    "fabrikarb.": "Fabrikarbeiter",
    "farbarb.": "Farbarbeiter",
    "fbkarb.": "Fabrikarbeiter",
    "färberges.": "Färbergeselle",
    "gerberges.": "Gerber Geselle",
    "ges.": "geselle",
    "giesserges.": "Gießer Geselle",
    "glasermstr.": "Glasermstr.",
    "gypserges.": "Gipser Geselle",
    "gärtnergeh.": "Gärtnergehilfe",
    "gärtnergehg.": "Gärtnergehilfe",
    "gärtnerges.": "Gärtner Geselle",
    "hafnerges.": "Hafner Geselle",
    "hafnermstr.": "Hafnermeister",
    "handl.": "handel",
    "haushält.": "Haushälter",
    "händl.": "händler",
    "jur.": "jurist",
    "kaufm.": "Kaufmännischer Angestellter",
    "kfm.": "Kaufmann",
    "kostgeb.": "Kostgänger",
    "küferges.": "Küfer Geselle",
    "küfermstr.": "Küfermeister",
    "ladengeh.": "Ladengehilfe",
    "lithogr.": "Lithograph",
    "magazinarb.": "Magazinarbeiter",
    "malerges.": "Maler Geselle",
    "malermstr.": "Malermeister",
    "maurerges.": "Maurergeselle",
    "maurermstr.": "Maurermeister",
    "mech.-ges.": "Mechaniker Geselle",
    "metzgermstr.": "Metzgermeister",
    "mstr.": "mesiter",
    "packtr.": "Packträger",
    "part.": "Partner",
    "partik.": "Partikular",
    "partikul.": "Partikular",
    "pos.": "Post",
    "posam.": "Postamt",
    "procuratr.": "Prokurist",
    "prof.": "Professor",
    "prokuratr.": "Prokurator",
    "rent.": "Miete",
    "sattlermstr.": "Sattlermeister",
    "schlosserges.": "Schlosser Geselle",
    "schlossermstr.": "Schlossermeister",
    "schmiedges.": "Schmied Geselle",
    "schneiderges.": "Schneider Geselle",
    "schneidermstr.": "Schneidermeister",
    "schreinererges.": "Schreinerergeselle",
    "schreinerges.": "Schreiner Geselle",
    "schreinermeistr.": "Schreinermeister",
    "schreinermstr.": "Schreinermeister",
    "schuhmacherges.": "Schuhmacher Geselle",
    "schuhmachermeistr.": "Schuhmachermeister",
    "schuhmachermstr.": "Schuhmachermeister",
    "schuhmacherstr.": "Schuhmacherstraße",
    "silberbergarb.": "Silberarbeiter",
    "spenglerges.": "Spengler Geselle",
    "spenglermstr.": "Spenglermeister",
    "steinhauerges.": "Steinhauer Geselle",
    "stud.": "Student",
    "stuhlschreinerges.": "Stuhlschreiner Geselle",
    "tagl.": "Taglöhner",
    "tapezierermstr.": "Tapezierermeister",
    "u.": "unternehmen",
    "uhrmachermstr.": "Uhrmachermeister",
    "viehhdlr.": "Viehhändler",
    "wagnerges.": "Wagner Geselle",
    "weinhdlr.": "Weinhändler",
    "zettlermstr.": "Zettlermeister",
    "zimmerges.": "Zimmerer Geselle",
    "zimmermstr.": "Zimmermeister",
}
