LAST_NAME_PREFIXES_MAP = {
    "aus der": "AusDer",
    "dal": "Dal",
    "de": "De",
    "del": "Del",
    "della": "Della",
    "des": "Des",
    "de la": "DeLa",
    "la": "La",
    "le": "Le",
    "v.": "Von",
    "van": "Van",
    "van den": "VanDen",
    "van der": "VanDer",
    "von der": "VonDer",
    "vom": "Vom",
    "von": "Von",
    "zum": "Zum",
}
