STREET_NAME_SUFFIXES = {
    "acker",
    "allee",
    "anlage",
    "bach",
    "berg",
    "brücke",
    "burg",
    "damm",
    "feld",
    "gasse",
    "gässchen",
    "gässlein",
    "gässligraben",
    "halde",
    "hang",
    "hof",
    "land",
    "lände",
    "markt",
    "matte",
    "mätteli",
    "park",
    "passage",
    "pfad",
    "platz",
    "promenade",
    "rain",
    "ring",
    "schanze",
    "stadt",
    "steg",
    "tal",
    "teich",
    "turm",
    "weg",
    "weid",
}
STREET_NAME_SUFFIXES_ABBREVIATION_MAP = {
    "g": "gasse",
    "gässl": "gässlein",
    "gr": "graben",
    "pl": "platz",
    "str": "strasse",
    "vorst": "vorstadt",
    "vor": "vorstadt",
    "w": "weg",
}
