"""
Production prompts for dots.ocr-1.5 address book transcription.

Auto-generated by tools/export_prompts.py from the dots-ocr-prompt-tuning repo.
Best-of v11+v13, no C-strategy (constrained decoding) prompts.
"""


# ── Prompt texts (unique prompts only) ─────────────────────────────

PROMPT_TEXTS: dict[str, str] = {
    "G13_1886_visual_scan_cl_norob": (
        "Transcribe this German address book page. Number each entry. Join wrapped lines.\n"
        "Copy leading symbols exactly: ‡ — -\n"
        "Symbols appear in order: ‡ then — then -.\n"
        "Look at the horizontal marks at each line start: a single long stroke = —. A long stroke followed by a gap and a short stroke = — -. If only one mark of any length, output —.\n"
        "‡ is a small double-cross that appears before — in the leftmost position. Scan each line start carefully: if any cross-like mark appears before the em-dash, transcribe it as ‡. When in doubt, include ‡ rather than omit it. The first entry does not always have ‡.\n"
        "Many entries have no prefix symbol — they begin directly with the name. Do not add ‡, ●, or — to these entries.\n"
        "\n"
        "1. ‡—Name …\n"
        "2. — -Name …\n"
        "3. —Name …\n"
        "4. Name …\n"
        "\n"
        "Numbered entries only.\n"
    ),
    "G13_1891_strict_two_combo_faint_cl_norob": (
        "Transcribe this German address book page. Number each entry. Join wrapped lines.\n"
        "Copy leading symbols exactly: ‡ — -\n"
        "Symbols appear in order: ‡ then — then -.\n"
        "— - means exactly two marks are visible: one long, one short, separated by a small gap. If marks touch or there is only one continuous stroke, output — alone.\n"
        "The ‡ is a small double-cross that appears before — and may be faint in this document. Transcribe it even when you are unsure — a false positive ‡ is better than a missed one. The first entry does not always have ‡.\n"
        "Many entries have no prefix symbol — they begin directly with the name. Do not add ‡, ●, or — to these entries.\n"
        "\n"
        "1. ‡—Name …\n"
        "2. — -Name …\n"
        "3. —Name …\n"
        "4. Name …\n"
        "\n"
        "Numbered entries only.\n"
    ),
    "G13_1909_enforce_combo_faint_cl_fad": (
        "Transcribe this German address book page. Number each entry. Join wrapped lines.\n"
        "Some entries may appear faded or have damaged print. Transcribe these entries as accurately as possible, including their prefix symbols.\n"
        "Copy leading symbols exactly: ‡ — -\n"
        "Symbols appear in order: ‡ then — then -.\n"
        "CRITICAL: — alone and — - are two DIFFERENT prefixes. Count marks: one long mark only → output —. One long mark + one short mark → output — -. Collapsing — - into — is the single most common error. Double-check every — to see if a short - follows it.\n"
        "The ‡ is a small double-cross that appears before — and may be faint in this document. Transcribe it even when you are unsure — a false positive ‡ is better than a missed one. The first entry does not always have ‡.\n"
        "Many entries have no prefix symbol — they begin directly with the name. Do not add ‡, ●, or — to these entries.\n"
        "\n"
        "1. ‡—Name …\n"
        "2. — -Name …\n"
        "3. —Name …\n"
        "4. Name …\n"
        "\n"
        "Numbered entries only.\n"
    ),
    "G13_1924_count_explicit_hrcl_cl_norob": (
        "Transcribe this German address book page. Number each entry.\n"
        "If an entry wraps across printed lines, join it into one numbered line.\n"
        "Preserve all leading symbols: ● (bullet), ‡ (cross/dagger), — (em-dash), - (hyphen).\n"
        "Symbols appear in order: ● then ‡ then — then -.\n"
        "For each entry, count horizontal marks before the name: 0 marks = no dash prefix. 1 mark (long) = —. 2 marks (long + short) = — -. The short mark may be faint or close to the long mark. If in doubt whether 1 or 2 marks, output — -.\n"
        "‡ appears on roughly 20% of entries in this year. It is a small cross that can be faint. If you see ANY mark resembling a cross before — or a name, include ‡. Missing a ‡ is worse than adding one incorrectly. The first entry does not always have ‡.\n"
        "Many entries have no prefix symbol — they begin directly with the name. Do not add ‡, ●, or — to these entries.\n"
        "● is rare; include it only when clearly printed.\n"
        "\n"
        "Format:\n"
        "1. ‡Name, occupation, address\n"
        "2. — -Name, occupation, address\n"
        "3. ●‡— -Name, occupation, address\n"
        "4. Name, occupation, address\n"
        "\n"
        "Output all entries numbered. No other commentary.\n"
    ),
    "G13_1946_enforce_combo_faint_no_edge": (
        "Transcribe this German address book page. Number each entry. Join wrapped lines.\n"
        "Entries near column edges may be partially cut off or smudged. Include all visible prefix symbols even if faded.\n"
        "Copy leading symbols exactly: ● ‡ — -\n"
        "Symbols appear in order: ● then ‡ then — then -.\n"
        "CRITICAL: — alone and — - are two DIFFERENT prefixes. Count marks: one long mark only → output —. One long mark + one short mark → output — -. Collapsing — - into — is the single most common error. Double-check every — to see if a short - follows it.\n"
        "The ‡ is a small double-cross that appears before — and may be faint in this document. Transcribe it even when you are unsure — a false positive ‡ is better than a missed one. The first entry does not always have ‡.\n"
        "\n"
        "1. ●‡— -Name …\n"
        "2. ‡—Name …\n"
        "3. — -Name …\n"
        "4. Name …\n"
        "\n"
        "Numbered entries only.\n"
    ),
    "G13_1947_strict_two_two_pass_cl_edge": (
        "Transcribe this German address book page. Number each entry. Join wrapped lines.\n"
        "Entries near column edges may be partially cut off or smudged. Include all visible prefix symbols even if faded.\n"
        "Copy leading symbols exactly: ● ‡ — -\n"
        "Symbols appear in order: ● then ‡ then — then -.\n"
        "— - means exactly two marks are visible: one long, one short, separated by a small gap. If marks touch or there is only one continuous stroke, output — alone.\n"
        "After transcribing, review each line start: if there is any mark between the line number area and the — that could be ‡, add it. ‡ is a small double-barred cross, sometimes compressed to look like a plus sign (+). The first entry does not always have ‡.\n"
        "Many entries have no prefix symbol — they begin directly with the name. Do not add ‡, ●, or — to these entries.\n"
        "\n"
        "1. ●‡— -Name …\n"
        "2. ‡—Name …\n"
        "3. — -Name …\n"
        "4. Name …\n"
        "\n"
        "Numbered entries only.\n"
    ),
    "G13_1948_count_explicit_two_pass_no_edge": (
        "Transcribe this German address book page. Number each entry. Join wrapped lines.\n"
        "Entries near column edges may be partially cut off or smudged. Include all visible prefix symbols even if faded.\n"
        "Copy leading symbols exactly: ● ‡ — -\n"
        "Symbols appear in order: ● then ‡ then — then -.\n"
        "For each entry, count horizontal marks before the name: 0 marks = no dash prefix. 1 mark (long) = —. 2 marks (long + short) = — -. The short mark may be faint or close to the long mark. If in doubt whether 1 or 2 marks, output — -.\n"
        "After transcribing, review each line start: if there is any mark between the line number area and the — that could be ‡, add it. ‡ is a small double-barred cross, sometimes compressed to look like a plus sign (+). The first entry does not always have ‡.\n"
        "\n"
        "1. ●‡— -Name …\n"
        "2. ‡—Name …\n"
        "3. — -Name …\n"
        "4. Name …\n"
        "\n"
        "Numbered entries only.\n"
    ),
    "G13_1949_strict_two_neg_anchor_no_norob": (
        "Transcribe this German address book page. Number each entry. Join wrapped lines.\n"
        "Copy leading symbols exactly: ● ‡ — -\n"
        "Symbols appear in order: ● then ‡ then — then -.\n"
        "— - means exactly two marks are visible: one long, one short, separated by a small gap. If marks touch or there is only one continuous stroke, output — alone.\n"
        "If you see — at the start with NO mark before it, output just —. If you see ANY small cross, asterisk, or plus-like mark before —, output ‡ —. ‡ is more common than you might expect. The first entry does not always have ‡.\n"
        "\n"
        "1. ●‡— -Name …\n"
        "2. ‡—Name …\n"
        "3. — -Name …\n"
        "4. Name …\n"
        "\n"
        "Numbered entries only.\n"
    ),
    "G13_1951_enforce_hrcl_cl_norob": (
        "Transcribe this German address book page. Number each entry. Join wrapped lines.\n"
        "Copy leading symbols exactly: ● ‡ — -\n"
        "Symbols appear in order: ● then ‡ then — then -.\n"
        "CRITICAL: — alone and — - are two DIFFERENT prefixes. Count marks: one long mark only → output —. One long mark + one short mark → output — -. Collapsing — - into — is the single most common error. Double-check every — to see if a short - follows it.\n"
        "‡ appears on roughly 20% of entries in this year. It is a small cross that can be faint. If you see ANY mark resembling a cross before — or a name, include ‡. Missing a ‡ is worse than adding one incorrectly. The first entry does not always have ‡.\n"
        "Many entries have no prefix symbol — they begin directly with the name. Do not add ‡, ●, or — to these entries.\n"
        "\n"
        "1. ●‡— -Name …\n"
        "2. ‡—Name …\n"
        "3. — -Name …\n"
        "4. Name …\n"
        "\n"
        "Numbered entries only.\n"
    ),
    "G13_1953_count_explicit_scan_no_edge": (
        "Transcribe this German address book page. Number each entry. Join wrapped lines.\n"
        "Entries near column edges may be partially cut off or smudged. Include all visible prefix symbols even if faded.\n"
        "Copy leading symbols exactly: ● ‡ — -\n"
        "Symbols appear in order: ● then ‡ then — then -.\n"
        "For each entry, count horizontal marks before the name: 0 marks = no dash prefix. 1 mark (long) = —. 2 marks (long + short) = — -. The short mark may be faint or close to the long mark. If in doubt whether 1 or 2 marks, output — -.\n"
        "‡ is a small double-cross that appears before — in the leftmost position. Scan each line start carefully: if any cross-like mark appears before the em-dash, transcribe it as ‡. When in doubt, include ‡ rather than omit it. The first entry does not always have ‡.\n"
        "\n"
        "1. ●‡— -Name …\n"
        "2. ‡—Name …\n"
        "3. — -Name …\n"
        "4. Name …\n"
        "\n"
        "Numbered entries only.\n"
    ),
    "G8_late_bid_gly_cl": (
        "Transcribe this German address book page. Number each entry.\n"
        "If an entry wraps across printed lines, join it into one numbered line.\n"
        "Preserve all leading symbols: ● (bullet), ‡ (cross/dagger), — (em-dash), - (hyphen).\n"
        "Symbols appear in order: ● then ‡ then — then -.\n"
        "Output — - only when both marks are visible; — alone otherwise. — alone and — - are different prefixes.\n"
        "‡ is a small cross with two horizontal bars on a vertical stroke. In this address book it may appear faint or compressed. If you see any cross-like mark before a name at the line start, transcribe it as ‡. The first entry does not always have ‡.\n"
        "Many entries have no prefix symbol — they begin directly with the name. Do not add ‡, ●, or — to these entries.\n"
        "● is rare; include it only when clearly printed.\n"
        "\n"
        "Format:\n"
        "1. ‡Name, occupation, address\n"
        "2. — -Name, occupation, address\n"
        "3. ●‡— -Name, occupation, address\n"
        "4. Name, occupation, address\n"
        "\n"
        "Output all entries numbered. No other commentary.\n"
    ),
    "G8_middle_len_cmt_cl": (
        "Transcribe this German address book page. Number each entry. Join wrapped lines.\n"
        "Copy leading symbols exactly: ‡ — -\n"
        "Symbols appear in order: ‡ then — then -.\n"
        "The — is a long horizontal mark; - is short. Output both only when both lengths appear; — alone otherwise.\n"
        "‡ appears on approximately 10% of entries. Include ‡ when you see it; omit when absent. When a mark before a name could be ‡ or a printing artifact, include ‡. The first entry does not always have ‡.\n"
        "Many entries have no prefix symbol — they begin directly with the name. Do not add ‡, ●, or — to these entries.\n"
        "\n"
        "1. ‡—Name …\n"
        "2. — -Name …\n"
        "3. —Name …\n"
        "4. Name …\n"
        "\n"
        "Numbered entries only.\n"
    ),
    "G8_middle_len_rar_cl": (
        "Transcribe this German address book page. Number each entry. Join wrapped lines.\n"
        "Copy leading symbols exactly: ‡ — -\n"
        "Symbols appear in order: ‡ then — then -.\n"
        "The — is a long horizontal mark; - is short. Output both only when both lengths appear; — alone otherwise.\n"
        "Include ‡ when present; omit it when absent. Most entries do not have ‡. The first entry does not always have ‡.\n"
        "Many entries have no prefix symbol — they begin directly with the name. Do not add ‡, ●, or — to these entries.\n"
        "\n"
        "1. ‡—Name …\n"
        "2. — -Name …\n"
        "3. —Name …\n"
        "4. Name …\n"
        "\n"
        "Numbered entries only.\n"
    ),
    "G8_modern_len_cmt_cl": (
        "Transcribe this German address book page. Number each entry. Join wrapped lines.\n"
        "Copy leading symbols exactly: ● ‡ — -\n"
        "Symbols appear in order: ● then ‡ then — then -.\n"
        "The — is a long horizontal mark; - is short. Output both only when both lengths appear; — alone otherwise.\n"
        "‡ appears on approximately 25% of entries. Include ‡ when you see it; omit when absent. When a mark before a name could be ‡ or a printing artifact, include ‡. The first entry does not always have ‡.\n"
        "Many entries have no prefix symbol — they begin directly with the name. Do not add ‡, ●, or — to these entries.\n"
        "\n"
        "1. ●‡— -Name …\n"
        "2. ‡—Name …\n"
        "3. — -Name …\n"
        "4. Name …\n"
        "\n"
        "Numbered entries only.\n"
    ),
    "G9X_1919_visual_anchor_nc_norob": (
        "Transcribe this German address book page. Number each entry.\n"
        "If an entry wraps across printed lines, join it into one numbered line.\n"
        "Preserve all leading symbols: ● (bullet), ‡ (cross/dagger), — (em-dash), - (hyphen).\n"
        "Symbols appear in order: ● then ‡ then — then -.\n"
        "Look at the horizontal marks at each line start: a single long stroke = —. A long stroke followed by a gap and a short stroke = — -. If only one mark of any length, output —.\n"
        "‡ always appears immediately before —. Check the character directly left of every —. If a small cross or mark is there, include ‡. If the space is empty, omit ‡. The first entry does not always have ‡.\n"
        "● is rare; include it only when clearly printed.\n"
        "\n"
        "Format:\n"
        "1. ‡Name, occupation, address\n"
        "2. — -Name, occupation, address\n"
        "3. ●‡— -Name, occupation, address\n"
        "4. Name, occupation, address\n"
        "\n"
        "Output all entries numbered. No other commentary.\n"
    ),
    "G9X_1920_visual_std_nc_norob": (
        "Transcribe this German address book page. Number each entry.\n"
        "If an entry wraps across printed lines, join it into one numbered line.\n"
        "Preserve all leading symbols: ● (bullet), ‡ (cross/dagger), — (em-dash), - (hyphen).\n"
        "Symbols appear in order: ● then ‡ then — then -.\n"
        "Look at the horizontal marks at each line start: a single long stroke = —. A long stroke followed by a gap and a short stroke = — -. If only one mark of any length, output —.\n"
        "Include ‡ when present; omit it when absent. The first entry does not always have ‡.\n"
        "● is rare; include it only when clearly printed.\n"
        "\n"
        "Format:\n"
        "1. ‡Name, occupation, address\n"
        "2. — -Name, occupation, address\n"
        "3. ●‡— -Name, occupation, address\n"
        "4. Name, occupation, address\n"
        "\n"
        "Output all entries numbered. No other commentary.\n"
    ),
    "G9X_1935_tri_combo_faint_cl_edge": (
        "Transcribe this German address book page. Number each entry. Join wrapped lines.\n"
        "Entries near column edges may be partially cut off or smudged. Include all visible prefix symbols even if faded.\n"
        "Copy leading symbols exactly: ● ‡ — -\n"
        "Symbols appear in order: ● then ‡ then — then -.\n"
        "The — is a long horizontal mark; - is short. Output — - only when both marks are visible; — alone otherwise. — alone and — - are different prefixes. Do not collapse — - into —.\n"
        "The ‡ is a small double-cross that appears before — and may be faint in this document. Transcribe it even when you are unsure — a false positive ‡ is better than a missed one. The first entry does not always have ‡.\n"
        "Many entries have no prefix symbol — they begin directly with the name. Do not add ‡, ●, or — to these entries.\n"
        "\n"
        "1. ●‡— -Name …\n"
        "2. ‡—Name …\n"
        "3. — -Name …\n"
        "4. Name …\n"
        "\n"
        "Numbered entries only.\n"
    ),
    "G9X_1939_tri_neg_anchor_cl_norob": (
        "Transcribe this German address book page. Number each entry. Join wrapped lines.\n"
        "Copy leading symbols exactly: ● ‡ — -\n"
        "Symbols appear in order: ● then ‡ then — then -.\n"
        "The — is a long horizontal mark; - is short. Output — - only when both marks are visible; — alone otherwise. — alone and — - are different prefixes. Do not collapse — - into —.\n"
        "If you see — at the start with NO mark before it, output just —. If you see ANY small cross, asterisk, or plus-like mark before —, output ‡ —. ‡ is more common than you might expect. The first entry does not always have ‡.\n"
        "Many entries have no prefix symbol — they begin directly with the name. Do not add ‡, ●, or — to these entries.\n"
        "\n"
        "1. ●‡— -Name …\n"
        "2. ‡—Name …\n"
        "3. — -Name …\n"
        "4. Name …\n"
        "\n"
        "Numbered entries only.\n"
    ),
    "G9_1885_expn_rar_nc_edge_3x": (
        "Transcribe this German address book page. Number each entry. Join wrapped lines.\n"
        "Entries near column edges may be partially cut off or smudged. Include all visible prefix symbols even if faded.\n"
        "Copy leading symbols exactly: ‡ — -\n"
        "Symbols appear in order: ‡ then — then -.\n"
        "The — is a long horizontal mark; - is short. When ONLY the long mark appears, output — alone. When BOTH a long AND short mark appear, output — -. NEVER output — - when only one mark is visible. NEVER output just — when two marks are visible.\n"
        "Include ‡ when present; omit it when absent. Most entries do not have ‡. The first entry does not always have ‡.\n"
        "\n"
        "1. ‡—Name …\n"
        "2. — -Name …\n"
        "3. Name …\n"
        "\n"
        "Numbered entries only.\n"
    ),
    "G9_1888_cnt_anchor_nc_fad": (
        "Transcribe this German address book page. Number each entry. Join wrapped lines.\n"
        "Some entries may appear faded or have damaged print. Transcribe these entries as accurately as possible, including their prefix symbols.\n"
        "Copy leading symbols exactly: ‡ — -\n"
        "Symbols appear in order: ‡ then — then -.\n"
        "Count the horizontal marks at the start of each entry. One long mark → —. One long mark followed by one short mark → — -. No marks → no dash prefix.\n"
        "‡ always appears immediately before —. Check the character directly left of every —. If a small cross or mark is there, include ‡. If the space is empty, omit ‡. The first entry does not always have ‡.\n"
        "\n"
        "1. ‡—Name …\n"
        "2. — -Name …\n"
        "3. —Name …\n"
        "4. Name …\n"
        "\n"
        "Numbered entries only.\n"
    ),
    "G9_1895_len_scan_nc_norob": (
        "Transcribe this German address book page. Number each entry. Join wrapped lines.\n"
        "Copy leading symbols exactly: ‡ — -\n"
        "Symbols appear in order: ‡ then — then -.\n"
        "The — is a long horizontal mark; - is short. Output both only when both lengths appear; — alone otherwise.\n"
        "‡ is a small double-cross that appears before — in the leftmost position. Scan each line start carefully: if any cross-like mark appears before the em-dash, transcribe it as ‡. When in doubt, include ‡ rather than omit it. The first entry does not always have ‡.\n"
        "\n"
        "1. ‡—Name …\n"
        "2. — -Name …\n"
        "3. —Name …\n"
        "4. Name …\n"
        "\n"
        "Numbered entries only.\n"
    ),
    "G9_1899_bid_scan_nc_norob": (
        "Transcribe this German address book page. Number each entry. Join wrapped lines.\n"
        "Copy leading symbols exactly: ‡ — -\n"
        "Symbols appear in order: ‡ then — then -.\n"
        "Output — - only when both marks are visible; — alone otherwise. — alone and — - are different prefixes.\n"
        "‡ is a small double-cross that appears before — in the leftmost position. Scan each line start carefully: if any cross-like mark appears before the em-dash, transcribe it as ‡. When in doubt, include ‡ rather than omit it. The first entry does not always have ‡.\n"
        "\n"
        "1. ‡—Name …\n"
        "2. — -Name …\n"
        "3. —Name …\n"
        "4. Name …\n"
        "\n"
        "Numbered entries only.\n"
    ),
    "G9_1900_len_rar_nc_norob_pro": (
        "Transcribe this German address book page. Number each entry.\n"
        "If an entry wraps across printed lines, join it into one numbered line.\n"
        "Preserve all leading symbols: ‡ (cross/dagger), — (em-dash), - (hyphen).\n"
        "Symbols appear in order: ‡ then — then -.\n"
        "The — is a long horizontal mark; - is short. Output both only when both lengths appear; — alone otherwise.\n"
        "Include ‡ when present; omit it when absent. Most entries do not have ‡. The first entry does not always have ‡.\n"
        "\n"
        "Format:\n"
        "1. ‡Name, occupation, address\n"
        "2. — -Name, occupation, address\n"
        "3. —Name, occupation, address\n"
        "4. Name, occupation, address\n"
        "\n"
        "Output all entries numbered. No other commentary.\n"
    ),
    "G9_1912_lb_slt_cl_edge": (
        "Transcribe this German address book page. Number each entry. Join wrapped lines.\n"
        "Entries near column edges may be partially cut off or smudged. Include all visible prefix symbols even if faded.\n"
        "Copy leading symbols exactly: ‡ — -\n"
        "Symbols appear in order: ‡ then — then -.\n"
        "The — is a long horizontal mark; - is short. Output both only when both lengths appear; — alone otherwise. — alone and — - are different prefixes.\n"
        "For each entry, check the leftmost position before — or the name. If a small cross (‡) appears there, include it. The symbol order is always: ‡ then — then -. The first entry does not always have ‡.\n"
        "Many entries have no prefix symbol — they begin directly with the name. Do not add ‡, ●, or — to these entries.\n"
        "\n"
        "1. ‡—Name …\n"
        "2. — -Name …\n"
        "3. —Name …\n"
        "4. Name …\n"
        "\n"
        "Numbered entries only.\n"
    ),
    "G9_1914_cnt_anchor_nc_edge": (
        "Transcribe this German address book page. Number each entry. Join wrapped lines.\n"
        "Entries near column edges may be partially cut off or smudged. Include all visible prefix symbols even if faded.\n"
        "Copy leading symbols exactly: ‡ — -\n"
        "Symbols appear in order: ‡ then — then -.\n"
        "Count the horizontal marks at the start of each entry. One long mark → —. One long mark followed by one short mark → — -. No marks → no dash prefix.\n"
        "‡ always appears immediately before —. Check the character directly left of every —. If a small cross or mark is there, include ‡. If the space is empty, omit ‡. The first entry does not always have ‡.\n"
        "\n"
        "1. ‡—Name …\n"
        "2. — -Name …\n"
        "3. —Name …\n"
        "4. Name …\n"
        "\n"
        "Numbered entries only.\n"
    ),
    "G9_1921_expn_frq_nc_edge": (
        "Transcribe this German address book page. Number each entry.\n"
        "If an entry wraps across printed lines, join it into one numbered line.\n"
        "Entries near column edges may be partially cut off or smudged. Include all visible prefix symbols even if faded.\n"
        "Preserve all leading symbols: ● (bullet), ‡ (cross/dagger), — (em-dash), - (hyphen).\n"
        "Symbols appear in order: ● then ‡ then — then -.\n"
        "The — is a long horizontal mark; - is short. When ONLY the long mark appears, output — alone. When BOTH a long AND short mark appear, output — -. NEVER output — - when only one mark is visible. NEVER output just — when two marks are visible.\n"
        "‡ appears on roughly a quarter of entries. Include it when present; omit it when absent. The first entry does not always have ‡.\n"
        "● is rare; include it only when clearly printed.\n"
        "\n"
        "Format:\n"
        "1. ‡Name, occupation, address\n"
        "2. — -Name, occupation, address\n"
        "3. ●‡— -Name, occupation, address\n"
        "4. Name, occupation, address\n"
        "\n"
        "Output all entries numbered. No other commentary.\n"
    ),
    "G9_1930_tri_rar_nc_norob": (
        "Transcribe this German address book page. Number each entry.\n"
        "If an entry wraps across printed lines, join it into one numbered line.\n"
        "Preserve all leading symbols: ● (bullet), ‡ (cross/dagger), — (em-dash), - (hyphen).\n"
        "Symbols appear in order: ● then ‡ then — then -.\n"
        "The — is a long horizontal mark; - is short. Output — - only when both marks are visible; — alone otherwise. — alone and — - are different prefixes. Do not collapse — - into —.\n"
        "Include ‡ when present; omit it when absent. Most entries do not have ‡. The first entry does not always have ‡.\n"
        "● is rare; include it only when clearly printed.\n"
        "\n"
        "Format:\n"
        "1. ‡Name, occupation, address\n"
        "2. — -Name, occupation, address\n"
        "3. ●‡— -Name, occupation, address\n"
        "4. Name, occupation, address\n"
        "\n"
        "Output all entries numbered. No other commentary.\n"
    ),
    "G9_1938_cnt_anchor_nc_edge": (
        "Transcribe this German address book page. Number each entry. Join wrapped lines.\n"
        "Entries near column edges may be partially cut off or smudged. Include all visible prefix symbols even if faded.\n"
        "Copy leading symbols exactly: ● ‡ — -\n"
        "Symbols appear in order: ● then ‡ then — then -.\n"
        "Count the horizontal marks at the start of each entry. One long mark → —. One long mark followed by one short mark → — -. No marks → no dash prefix.\n"
        "‡ always appears immediately before —. Check the character directly left of every —. If a small cross or mark is there, include ‡. If the space is empty, omit ‡. The first entry does not always have ‡.\n"
        "\n"
        "1. ●‡— -Name …\n"
        "2. ‡—Name …\n"
        "3. — -Name …\n"
        "4. Name …\n"
        "\n"
        "Numbered entries only.\n"
    ),
    "G9_1943_bid_std_nc_edge": (
        "Transcribe this German address book page. Number each entry. Join wrapped lines.\n"
        "Entries near column edges may be partially cut off or smudged. Include all visible prefix symbols even if faded.\n"
        "Copy leading symbols exactly: ● ‡ — -\n"
        "Symbols appear in order: ● then ‡ then — then -.\n"
        "Output — - only when both marks are visible; — alone otherwise. — alone and — - are different prefixes.\n"
        "Include ‡ when present; omit it when absent. The first entry does not always have ‡.\n"
        "\n"
        "1. ●‡— -Name …\n"
        "2. ‡—Name …\n"
        "3. — -Name …\n"
        "4. Name …\n"
        "\n"
        "Numbered entries only.\n"
    ),
    "G_middle_com_len_std_nofe_rob_bp_4ex": (
        "Transcribe this German address book page. Number each entry. Join wrapped lines.\n"
        "Transcribe all entries even if the print is faded or partially legible.\n"
        "Copy leading symbols exactly: ‡ — -\n"
        "Symbols appear in order: ‡ then — then -.\n"
        "The — is a long horizontal mark; - is short. Output both only when both lengths appear; — alone otherwise.\n"
        "Include ‡ when present; omit it when absent.\n"
        "\n"
        "1. ‡—Name …\n"
        "2. — -Name …\n"
        "3. —Name …\n"
        "4. Name …\n"
        "\n"
        "Numbered entries only.\n"
    ),
    "G_modern_com_lb_std_fe_nor_bp_5ex": (
        "Transcribe this German address book page. Number each entry. Join wrapped lines.\n"
        "Copy leading symbols exactly: ● ‡ — -\n"
        "Symbols appear in order: ● then ‡ then — then -.\n"
        "The — is a long horizontal mark; - is short. Output both only when both lengths appear; — alone otherwise. — alone and — - are different prefixes.\n"
        "Include ‡ when present; omit it when absent. The first entry does not always have ‡.\n"
        "\n"
        "1. ●‡— -Name …\n"
        "2. ‡—Name …\n"
        "3. — -Name …\n"
        "4. —Name …\n"
        "5. Name …\n"
        "\n"
        "Numbered entries only.\n"
    ),
    "V10_1887_cnt_std_nc_edge": (
        "Transcribe this German address book page. Number each entry. Join wrapped lines.\n"
        "Entries near column edges may be partially cut off or smudged. Include all visible prefix symbols even if faded.\n"
        "Copy leading symbols exactly: ‡ — -\n"
        "Symbols appear in order: ‡ then — then -.\n"
        "Count the horizontal marks at the start of each entry. One long mark → —. One long mark followed by one short mark → — -. No marks → no dash prefix.\n"
        "Include ‡ when present; omit it when absent. The first entry does not always have ‡.\n"
        "\n"
        "1. ‡—Name …\n"
        "2. — -Name …\n"
        "3. —Name …\n"
        "4. Name …\n"
        "\n"
        "Numbered entries only.\n"
    ),
    "V10_1889_expn_rar_cl_edge_p0cons": (
        "Transcribe this German address book page. Number each entry. Join wrapped lines.\n"
        "Entries near column edges may be partially cut off or smudged. Include all visible prefix symbols even if faded.\n"
        "Copy leading symbols exactly: ‡ — -\n"
        "Symbols appear in order: ‡ then — then -.\n"
        "The — is a long horizontal mark; - is short. When ONLY the long mark appears, output — alone. When BOTH a long AND short mark appear, output — -. NEVER output — - when only one mark is visible. NEVER output just — when two marks are visible.\n"
        "Include ‡ when present; omit it when absent. Most entries do not have ‡. The first entry does not always have ‡.\n"
        "Many entries have no prefix symbol — they begin directly with the name. Do not add ‡, ●, or — to these entries.\n"
        "\n"
        "1. ‡—Name …\n"
        "2. — -Name …\n"
        "3. —Name …\n"
        "4. Name …\n"
        "\n"
        "Numbered entries only.\n"
    ),
    "V10_1893_tri_rar_cl_edge_p0head": (
        "Transcribe this German address book page. Number each entry. Join wrapped lines.\n"
        "Entries near column edges may be partially cut off or smudged. Include all visible prefix symbols even if faded.\n"
        "Copy leading symbols exactly: ‡ — -\n"
        "Symbols appear in order: ‡ then — then -.\n"
        "The — is a long horizontal mark; - is short. Output — - only when both marks are visible; — alone otherwise. — alone and — - are different prefixes. Do not collapse — - into —.\n"
        "Include ‡ when present; omit it when absent. Most entries do not have ‡. The first entry does not always have ‡.\n"
        "Many entries have no prefix symbol — they begin directly with the name. Do not add ‡, ●, or — to these entries.\n"
        "\n"
        "1. ‡—Name …\n"
        "2. — -Name …\n"
        "3. —Name …\n"
        "4. Name …\n"
        "\n"
        "Numbered entries only.\n"
    ),
    "V10_1901_cnt_rar_cl_fad": (
        "Transcribe this German address book page. Number each entry. Join wrapped lines.\n"
        "Some entries may appear faded or have damaged print. Transcribe these entries as accurately as possible, including their prefix symbols.\n"
        "Copy leading symbols exactly: ‡ — -\n"
        "Symbols appear in order: ‡ then — then -.\n"
        "Count the horizontal marks at the start of each entry. One long mark → —. One long mark followed by one short mark → — -. No marks → no dash prefix.\n"
        "Include ‡ when present; omit it when absent. Most entries do not have ‡. The first entry does not always have ‡.\n"
        "Many entries have no prefix symbol — they begin directly with the name. Do not add ‡, ●, or — to these entries.\n"
        "\n"
        "1. ‡—Name …\n"
        "2. — -Name …\n"
        "3. —Name …\n"
        "4. Name …\n"
        "\n"
        "Numbered entries only.\n"
    ),
    "V10_1902_cnt_rar_cl_fad": (
        "Transcribe this German address book page. Number each entry. Join wrapped lines.\n"
        "Some entries may appear faded or have damaged print. Transcribe these entries as accurately as possible, including their prefix symbols.\n"
        "Copy leading symbols exactly: ‡ — -\n"
        "Symbols appear in order: ‡ then — then -.\n"
        "Count the horizontal marks at the start of each entry. One long mark → —. One long mark followed by one short mark → — -. No marks → no dash prefix.\n"
        "Include ‡ when present; omit it when absent. Most entries do not have ‡. The first entry does not always have ‡.\n"
        "Many entries have no prefix symbol — they begin directly with the name. Do not add ‡, ●, or — to these entries.\n"
        "\n"
        "1. ‡—Name …\n"
        "2. — -Name …\n"
        "3. —Name …\n"
        "4. Name …\n"
        "\n"
        "Numbered entries only.\n"
    ),
    "V10_1904_cnt_std_nc_fad": (
        "Transcribe this German address book page. Number each entry. Join wrapped lines.\n"
        "Some entries may appear faded or have damaged print. Transcribe these entries as accurately as possible, including their prefix symbols.\n"
        "Copy leading symbols exactly: ‡ — -\n"
        "Symbols appear in order: ‡ then — then -.\n"
        "Count the horizontal marks at the start of each entry. One long mark → —. One long mark followed by one short mark → — -. No marks → no dash prefix.\n"
        "Include ‡ when present; omit it when absent. The first entry does not always have ‡.\n"
        "\n"
        "1. ‡—Name …\n"
        "2. — -Name …\n"
        "3. —Name …\n"
        "4. Name …\n"
        "\n"
        "Numbered entries only.\n"
    ),
    "V10_1910_expn_std_cl_edge_p0head": (
        "Transcribe this German address book page. Number each entry. Join wrapped lines.\n"
        "Entries near column edges may be partially cut off or smudged. Include all visible prefix symbols even if faded.\n"
        "Copy leading symbols exactly: ‡ — -\n"
        "Symbols appear in order: ‡ then — then -.\n"
        "The — is a long horizontal mark; - is short. When ONLY the long mark appears, output — alone. When BOTH a long AND short mark appear, output — -. NEVER output — - when only one mark is visible. NEVER output just — when two marks are visible.\n"
        "Include ‡ when present; omit it when absent. The first entry does not always have ‡.\n"
        "Many entries have no prefix symbol — they begin directly with the name. Do not add ‡, ●, or — to these entries.\n"
        "\n"
        "1. ‡—Name …\n"
        "2. — -Name …\n"
        "3. —Name …\n"
        "4. Name …\n"
        "\n"
        "Numbered entries only.\n"
    ),
    "V10_1913_cnt_std_cl_norob": (
        "Transcribe this German address book page. Number each entry. Join wrapped lines.\n"
        "Copy leading symbols exactly: ‡ — -\n"
        "Symbols appear in order: ‡ then — then -.\n"
        "Count the horizontal marks at the start of each entry. One long mark → —. One long mark followed by one short mark → — -. No marks → no dash prefix.\n"
        "Include ‡ when present; omit it when absent. The first entry does not always have ‡.\n"
        "Many entries have no prefix symbol — they begin directly with the name. Do not add ‡, ●, or — to these entries.\n"
        "\n"
        "1. ‡—Name …\n"
        "2. — -Name …\n"
        "3. —Name …\n"
        "4. Name …\n"
        "\n"
        "Numbered entries only.\n"
    ),
    "V10_1916_strict_two_std_cl_fad": (
        "Transcribe this German address book page. Number each entry. Join wrapped lines.\n"
        "Some entries may appear faded or have damaged print. Transcribe these entries as accurately as possible, including their prefix symbols.\n"
        "Copy leading symbols exactly: ‡ — -\n"
        "Symbols appear in order: ‡ then — then -.\n"
        "— - means exactly two marks are visible: one long, one short, separated by a small gap. If marks touch or there is only one continuous stroke, output — alone.\n"
        "Include ‡ when present; omit it when absent. The first entry does not always have ‡.\n"
        "Many entries have no prefix symbol — they begin directly with the name. Do not add ‡, ●, or — to these entries.\n"
        "\n"
        "1. ‡—Name …\n"
        "2. — -Name …\n"
        "3. —Name …\n"
        "4. Name …\n"
        "\n"
        "Numbered entries only.\n"
    ),
    "V10_1942_cnt_std_cl_norob": (
        "Transcribe this German address book page. Number each entry. Join wrapped lines.\n"
        "Copy leading symbols exactly: ● ‡ — -\n"
        "Symbols appear in order: ● then ‡ then — then -.\n"
        "Count the horizontal marks at the start of each entry. One long mark → —. One long mark followed by one short mark → — -. No marks → no dash prefix.\n"
        "Include ‡ when present; omit it when absent. The first entry does not always have ‡.\n"
        "Many entries have no prefix symbol — they begin directly with the name. Do not add ‡, ●, or — to these entries.\n"
        "\n"
        "1. ●‡— -Name …\n"
        "2. ‡—Name …\n"
        "3. — -Name …\n"
        "4. Name …\n"
        "\n"
        "Numbered entries only.\n"
    ),
    "V10_1945_cnt_scan_no_edge": (
        "Transcribe this German address book page. Number each entry. Join wrapped lines.\n"
        "Entries near column edges may be partially cut off or smudged. Include all visible prefix symbols even if faded.\n"
        "Copy leading symbols exactly: ● ‡ — -\n"
        "Symbols appear in order: ● then ‡ then — then -.\n"
        "Count the horizontal marks at the start of each entry. One long mark → —. One long mark followed by one short mark → — -. No marks → no dash prefix.\n"
        "‡ is a small double-cross that appears before — in the leftmost position. Scan each line start carefully: if any cross-like mark appears before the em-dash, transcribe it as ‡. When in doubt, include ‡ rather than omit it. The first entry does not always have ‡.\n"
        "\n"
        "1. ●‡— -Name …\n"
        "2. ‡—Name …\n"
        "3. — -Name …\n"
        "4. Name …\n"
        "\n"
        "Numbered entries only.\n"
    ),
    "V11_1883_tri_rar_cl_edge_p0head": (
        "Transcribe this German address book page. Number each entry. Join wrapped lines.\n"
        "Entries near column edges may be partially cut off or smudged. Include all visible prefix symbols even if faded.\n"
        "Copy leading symbols exactly: ‡ — -\n"
        "Symbols appear in order: ‡ then — then -.\n"
        "The — is a long horizontal mark; - is short. Output — - only when both marks are visible; — alone otherwise. — alone and — - are different prefixes. Do not collapse — - into —.\n"
        "Include ‡ when present; omit it when absent. Most entries do not have ‡. The first entry does not always have ‡.\n"
        "Many entries have no prefix symbol — they begin directly with the name. Do not add ‡, ●, or — to these entries.\n"
        "\n"
        "1. ‡—Name …\n"
        "2. — -Name …\n"
        "3. —Name …\n"
        "4. Name …\n"
        "\n"
        "Numbered entries only.\n"
    ),
    "V11_1896_cnt_std_nc_edge": (
        "Transcribe this German address book page. Number each entry. Join wrapped lines.\n"
        "Entries near column edges may be partially cut off or smudged. Include all visible prefix symbols even if faded.\n"
        "Copy leading symbols exactly: ‡ — -\n"
        "Symbols appear in order: ‡ then — then -.\n"
        "Count the horizontal marks at the start of each entry. One long mark → —. One long mark followed by one short mark → — -. No marks → no dash prefix.\n"
        "Include ‡ when present; omit it when absent. The first entry does not always have ‡.\n"
        "\n"
        "1. ‡—Name …\n"
        "2. — -Name …\n"
        "3. —Name …\n"
        "4. Name …\n"
        "\n"
        "Numbered entries only.\n"
    ),
    "V11_1898_tri_scan_cl_fad": (
        "Transcribe this German address book page. Number each entry. Join wrapped lines.\n"
        "Some entries may appear faded or have damaged print. Transcribe these entries as accurately as possible, including their prefix symbols.\n"
        "Copy leading symbols exactly: ‡ — -\n"
        "Symbols appear in order: ‡ then — then -.\n"
        "The — is a long horizontal mark; - is short. Output — - only when both marks are visible; — alone otherwise. — alone and — - are different prefixes. Do not collapse — - into —.\n"
        "‡ is a small double-cross that appears before — in the leftmost position. Scan each line start carefully: if any cross-like mark appears before the em-dash, transcribe it as ‡. When in doubt, include ‡ rather than omit it. The first entry does not always have ‡.\n"
        "Many entries have no prefix symbol — they begin directly with the name. Do not add ‡, ●, or — to these entries.\n"
        "\n"
        "1. ‡—Name …\n"
        "2. — -Name …\n"
        "3. —Name …\n"
        "4. Name …\n"
        "\n"
        "Numbered entries only.\n"
    ),
}


# ── Year-to-prompt mapping ────────────────────────────────────────

YEAR_TO_PROMPT: dict[int, str] = {
    1877: "G9_1885_expn_rar_nc_edge_3x",
    1880: "G9_1885_expn_rar_nc_edge_3x",
    1883: "V11_1883_tri_rar_cl_edge_p0head",
    1884: "G9_1885_expn_rar_nc_edge_3x",
    1885: "G9_1885_expn_rar_nc_edge_3x",
    1886: "G13_1886_visual_scan_cl_norob",
    1887: "V10_1887_cnt_std_nc_edge",
    1888: "G9_1888_cnt_anchor_nc_fad",
    1889: "V10_1889_expn_rar_cl_edge_p0cons",
    1890: "G8_middle_len_cmt_cl",
    1891: "G13_1891_strict_two_combo_faint_cl_norob",
    1892: "G8_middle_len_cmt_cl",
    1893: "V10_1893_tri_rar_cl_edge_p0head",
    1894: "G9_1895_len_scan_nc_norob",
    1895: "G9_1895_len_scan_nc_norob",
    1896: "V11_1896_cnt_std_nc_edge",
    1897: "G9_1895_len_scan_nc_norob",
    1898: "V11_1898_tri_scan_cl_fad",
    1899: "G9_1899_bid_scan_nc_norob",
    1900: "G9_1900_len_rar_nc_norob_pro",
    1901: "V10_1901_cnt_rar_cl_fad",
    1902: "V10_1902_cnt_rar_cl_fad",
    1903: "G8_middle_len_rar_cl",
    1904: "V10_1904_cnt_std_nc_fad",
    1905: "G8_middle_len_rar_cl",
    1906: "G8_middle_len_rar_cl",
    1907: "G8_middle_len_rar_cl",
    1908: "G9_1900_len_rar_nc_norob_pro",
    1909: "G13_1909_enforce_combo_faint_cl_fad",
    1910: "V10_1910_expn_std_cl_edge_p0head",
    1911: "G9_1900_len_rar_nc_norob_pro",
    1912: "G9_1912_lb_slt_cl_edge",
    1913: "V10_1913_cnt_std_cl_norob",
    1914: "G9_1914_cnt_anchor_nc_edge",
    1915: "G_middle_com_len_std_nofe_rob_bp_4ex",
    1916: "V10_1916_strict_two_std_cl_fad",
    1917: "G_middle_com_len_std_nofe_rob_bp_4ex",
    1918: "G9X_1919_visual_anchor_nc_norob",
    1919: "G9X_1919_visual_anchor_nc_norob",
    1920: "G9X_1920_visual_std_nc_norob",
    1921: "G9_1921_expn_frq_nc_edge",
    1922: "G9X_1920_visual_std_nc_norob",
    1923: "G8_late_bid_gly_cl",
    1924: "G13_1924_count_explicit_hrcl_cl_norob",
    1925: "G8_late_bid_gly_cl",
    1926: "G8_late_bid_gly_cl",
    1927: "G8_late_bid_gly_cl",
    1928: "G9_1930_tri_rar_nc_norob",
    1929: "G9_1930_tri_rar_nc_norob",
    1930: "G9_1930_tri_rar_nc_norob",
    1931: "G9_1930_tri_rar_nc_norob",
    1932: "G9_1930_tri_rar_nc_norob",
    1933: "G9_1930_tri_rar_nc_norob",
    1934: "G9X_1935_tri_combo_faint_cl_edge",
    1935: "G9X_1935_tri_combo_faint_cl_edge",
    1936: "G9X_1935_tri_combo_faint_cl_edge",
    1937: "G9_1938_cnt_anchor_nc_edge",
    1938: "G9_1938_cnt_anchor_nc_edge",
    1939: "G9X_1939_tri_neg_anchor_cl_norob",
    1940: "G8_modern_len_cmt_cl",
    1941: "G9_1938_cnt_anchor_nc_edge",
    1942: "V10_1942_cnt_std_cl_norob",
    1943: "G9_1943_bid_std_nc_edge",
    1944: "G9_1943_bid_std_nc_edge",
    1945: "V10_1945_cnt_scan_no_edge",
    1946: "G13_1946_enforce_combo_faint_no_edge",
    1947: "G13_1947_strict_two_two_pass_cl_edge",
    1948: "G13_1948_count_explicit_two_pass_no_edge",
    1949: "G13_1949_strict_two_neg_anchor_no_norob",
    1950: "G_modern_com_lb_std_fe_nor_bp_5ex",
    1951: "G13_1951_enforce_hrcl_cl_norob",
    1952: "G_modern_com_lb_std_fe_nor_bp_5ex",
    1953: "G13_1953_count_explicit_scan_no_edge",
    1954: "G_modern_com_lb_std_fe_nor_bp_5ex",
}


def get_prompt(year: int) -> str:
    """Return the best prompt text for a given year.

    Falls back to the nearest available year if exact match not found.
    """
    if year in YEAR_TO_PROMPT:
        return PROMPT_TEXTS[YEAR_TO_PROMPT[year]]

    # Fallback: find nearest year
    available = sorted(YEAR_TO_PROMPT.keys())
    if not available:
        raise ValueError("No prompts available")
    closest = min(available, key=lambda y: abs(y - year))
    return PROMPT_TEXTS[YEAR_TO_PROMPT[closest]]
